set(SDK_PATH "/Volumes/Resources/git/gsdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.3")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../stash/wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/src/sl_si91x_button.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/src/sl_si91x_led.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "../../../../examples/platform/silabs/syscalls_stubs.cpp"
    "../../../../src/lib/support/Base64.cpp"
    "../../../../src/lib/support/BytesToHex.cpp"
    "../../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "../../../../src/platform/silabs/Logging.cpp"
    "../../../../src/platform/silabs/SilabsConfig.cpp"
    "../../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "../../../../src/setup_payload/Base38Encode.cpp"
    "../../../../third_party/mbedtls/repo/library/aes.c"
    "../../../../third_party/mbedtls/repo/library/asn1parse.c"
    "../../../../third_party/mbedtls/repo/library/asn1write.c"
    "../../../../third_party/mbedtls/repo/library/base64.c"
    "../../../../third_party/mbedtls/repo/library/bignum.c"
    "../../../../third_party/mbedtls/repo/library/ccm.c"
    "../../../../third_party/mbedtls/repo/library/cipher.c"
    "../../../../third_party/mbedtls/repo/library/cipher_wrap.c"
    "../../../../third_party/mbedtls/repo/library/constant_time.c"
    "../../../../third_party/mbedtls/repo/library/ctr_drbg.c"
    "../../../../third_party/mbedtls/repo/library/ecdh.c"
    "../../../../third_party/mbedtls/repo/library/ecdsa.c"
    "../../../../third_party/mbedtls/repo/library/ecp.c"
    "../../../../third_party/mbedtls/repo/library/ecp_curves.c"
    "../../../../third_party/mbedtls/repo/library/entropy.c"
    "../../../../third_party/mbedtls/repo/library/hkdf.c"
    "../../../../third_party/mbedtls/repo/library/hmac_drbg.c"
    "../../../../third_party/mbedtls/repo/library/md.c"
    "../../../../third_party/mbedtls/repo/library/pem.c"
    "../../../../third_party/mbedtls/repo/library/pkcs5.c"
    "../../../../third_party/mbedtls/repo/library/platform.c"
    "../../../../third_party/mbedtls/repo/library/sha256.c"
    "../../../../third_party/mbedtls/repo/library/sha512.c"
    "../../../../third_party/mbedtls/repo/library/x509.c"
    "../../../../third_party/mbedtls/repo/library/x509_create.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_si91x_button_instances.c"
    "../autogen/sl_si91x_led_instances.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
   "../../../../examples"
   "../../../../examples/platform/silabs"
   "../../../../src"
   "../../../../src/platform/silabs/SiWx917"
   "../../../../src/include"
   "../../../../zzz_generated/app-common"
   "../../../../third_party/nlassert/repo/include"
   "../../../../third_party/nlio/repo/include"
   "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/inc"
   "../../../../third_party/mbedtls/repo/library"
   "../../../../third_party/mbedtls/repo/include"
   "../../../../src/lib/support"
   "../../../../src/platform/silabs"
   "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../stash/wifi_sdk/resources/certificates"
    "${SDK_PATH}/../stash/wifi_sdk/resources/html"
    "${SDK_PATH}/../stash/wifi_sdk/resources/other"
    "${SDK_PATH}/../stash/wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=1
    SL_MBEDTLS_USE_TINYCRYPT=1
    SL_PROVISION_CHANNEL_ENABLED=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A06"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SL_SI91X_BOARD_INIT=1
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SI91X_PLATFORM=1
    SI91X_SYSRTC_PRESENT=1
    SL_SLEEP_TIMER=1
    __WEAK=__attribute__((weak))
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz3DaW7l9xqbZuze5KTUt2Xr7JTMmS7GjHslTqdjK5qy0Wm0R3c8VX+FBLmZr/fvHgEwRJgATA9uxmdxI1SZzvOwdv4ODg70d397f/cXWxMu9vb1dH747+/nB0f/XpfHX9y5VZf/Vw9O7haLF4OPrH0XGZZnn75f7iagmT/fiXZ9979QTixA2Dnx6OThevH45egcAOHTfYwgdfVh9Ovn84+sufH4Ifozj8b2Cnr2CSIHnnhw7w4Be7NI3eGcZ+v18krmetk4Ud+kaSGMs0c9xwAewwBlAoTB2BOH1Z2vC/MF0u7eEIin716sdN6DkgfhVYPnpph8HG3ebv0FvXA8W75dXHj1f35v1qZV7AzxY7KDyLXfgGffXO+CX0Mh8kxj1Iwiy24V9bNzV8K01BbMTAA1YCDIj+5CKljSSLojBOjcT94fQ7gwAbDAyDxSXxzACkpgM2Vual5pPlZSBRwqgTicnrQwzA/ep2eYETKyHUhuiyEEr2bHrAMW11dDpwmJzuV1fmJXhybWBCCUrotCG6rLMOrbhgnMVWCkWqMlAH1CCzNA495ZwKECabyA1UFp6m+P5yvM7SNAxMxYz64bgYrtPgtU6KFB4vx1PNHE95OHoARKnrg1g1ORZQv+WS1LIf4d9/AC2GY8IxGQLfc9cm6u1hL7XOtirp9WARbj8aZEDBGlxYWRpuQcAeXdAlxg2gBQLIcmHL1CPn0CqgDTiuKlSlkGroYYJcPb4u87WwRKipNVwLi0nNc4NHEKMn5jK8WHiOCk4MkM4B0kXoR2EAglSRfdoYXVlmF1+ZtpVaXii5SallGBOpixZ4Qh/urMDxQKyMUguFj46q2tZC6aLjhkkaA8vPv1VXyVhA3KRUmYkFNEjKDdxUQ6vUg8ekuLBju+hf4Z8qWLUghjvxvZsAmCIAdvrGTJxH883iDVq8KDWg1hOKhqb8ovWNg6drtfetL8j6RuMLxjewzac+aX3k21nrEwbnGDC+an+3cyPmd21uyLTMD1ufunc3X0yYbdvOBOwkTph2Y5BEtaIVJ66ZvCQp8PPcx5NlviIGi22yM/buxkXZb1Q5bJCMNEhu4ZL2bECLG8igBrKWAQ1hlBoaJXGjk4/Bq5Eb+ZlpRS5v06JCiwaHbuaN2iX+utGKEZthkpoUpyG79GzyTK04zSK9RGlMLqaoJEaJGcNmepMFtiauDFRutg6cyeLprJmEOvm2cNmMe4sz3ZIFfe0kpTeI45B3+DdFX0jKaOBx5cwadr9m+hJxjyemUmwCcnF04FhbK8cmIBfH++XpM/xHE8EaGnf9s+0IzV987uVjGYWxCcrPFcrQyTKHG9Xy6qNJoXKzbYxYNPJt4XIxhikIhCamDTxehlorUgOPl6GVJCBO9TGs8ERqkfYy2cDkGxPWB5J6iNKQfDzxYqLWqkNDCvD0n3Q18A084bFf36tel4Teb/sn2lQ1CaCWcArnhrGbuqAsv2pH0PkuTz6G7qYwajDNGJlkiehe2jTNOnA71OHMEl3Eu+FZ/EWKMOplFBRhvAenusQi7rVZX47I1yY1dzPDNfI8gjJsz4qBNt6DLDTPXIkNFRdqrH3RO5eI8trp7hfU6m7sIjc3rgVVP3ETkyTgqywXN8vrJe/S6mWfYMb314HtZQ57KbhKUstbAoA211SOYXODGnVrGdgQBiFg5MSNFh/u1dQi5fnnA1KDkBHV4Wr18+HokJMZoYN5c35xUHoUhMbocvfzb4elS05IVJcPHmR3OJqUdET1uD47oLKVkxHV4ebi+nB0yMmI6vD5/PPl4ShRsBHVYnl+QDmRkxHW4e6QdLgbpcOX5fn96nC0KOmI6/H+kLR4P1KHA6rZBZsRWhzQYKpgo2anXWT217tEJeMMhCRrDp6REDLBYcx8OCc5DbpX2gfTV72j5Qa5j9r7no+9HUyDnPaRYu9osEFN+wCwd5DXoAanF+an88/ff/f27FwvRxqZg6z24VvvEK1JTXfN4K8YXy5vNGdtgchDTv9IcGC0R9HTPMDrHcS1s1XVOnV3tnavSbezVS+7AnLahkgc+kLrvELL60i47T2qc2oqLFNpUS6017G59+tRIrCN3HAuxiU4v4uBZT+6gbpNjB7CNWghC9uxOp+ioRIRizkW4TTqfEyG2Ip5m+ACtMkSdc4RQ6W3ABeivHH9uQjn0EJ0t5HjW3MRLsGFKEfhHk7MEutptpLRZCBGfj9b8cihhej+nkTuXHwLbCHC8TydRw1aiG5qrT1gqnZGHiDeIjFCBbXudlwKiLnflWnRYf3ZiBfgQpSzGZvsbEyLjRKZ+9iKovlMTXMQU8CLkgQNwGdjXyeg0CkSGseNdiC2vJwF28FmvHeZ7YX2o5lFjpWqc9QqjNnWBvtt0Rz4jznE6g5CDXCuwXPTJdOvGQmXBESOPsTprEauGHCTxq24ugOiHKQrBtykcUM+I+UCX4hw2YDPTLzOg1+BxIrTWZkXBDT6pTbaWtWdJ0N31InSHITa+5k41+AF2/sZCYut91nZsxmDDYhBYAPzKfRS1X75Ayr0EuLOBcuZtdDk8ALHTNVP8PvKuC02x0eoVmylCo9o87BusOAnr37ttY+02PqrzR0oShFbsc0Ox5q12uXw/G21lpXtvrZaeHUbBDsUWMjRssTdx5ziwa3AzLxF6epZmu8hLL48v9WxXNzHWHTJ2D2btdXI4QXoztom5/D8dGftpF2xzjmMLF/dGWcOviUB/t1yDZtJPYRFN5R+B7M2Djk8P92ZGzPh/S+UAMUOS2edBDZZ8C+za9i462EtvHk3d+ccC3fOieOG6k+V9VAuCQhQ9sGsTVxJgJ/yvEswiaDDVeK785aJHJ+f8LyNsmibnMzNV5gw2f+Yk3LJQJC0uQOWg/ZBZidfZyK6jTQj+YqB2DbSjJSF/RG0+iIMEB/lj0B2ceZkXhDgpvxkOXMSzuG56e6zWL0rUw/fAl8sFI7/1oxmaz3aLBQ6qWQBJA4cFBJZsndKqQbRzdTiQFFTpxlWiCKhcdeWSUF10arboVGmKBK81WJm7lyspdYH5c5bZY7UkLRWkQ7nhj5ec9Qamoau0jfUODN4ifUxB6XNeBVUh4Mdo8lgyFgpTcXOip29hW7ZEmkgyFVRvPHQ+pqTrlwhCMrbEVp9g+A2G5GKS2fJGrpKgbv9GLCH6gLaZY9G6ay4jLKHSFPrAUdlKYPi9RcxCNosXzmL+QoXIqC9ZCEzNIpVzkJ2meJvCxMQIx34msDgyX+jsmiS1t/coFBrphukG+UFNVffQJo1CyiTS080HKZCSKy5gz0eFjOjNm0i2mseplDc9KzJx7FhEFTxOkiI5mu7cGjXpJ+L8k6quuNVUYNQ3SGLii1RVdPBiMLWFYeyMvWzmqE3cylO2gpizTikOLKYzNiv4dsIPPAEPAVRMNah+sFDTYNyUTTH5fcHTTQd7WSRrYPze0tFfjYL2wKY3+/I01DZGERzXH6eMxlU2J76Ihow6Y4LZxDFIeSThDApCBINDvlM7gwS/E48YKvFn4BFvIYtwDeFeK6GhQE24xo6P2cNzgRMtoIuBFBANGdBpvCFvAbwAuNM/TKFz7+Nre1IPYs1x3l61sbw3lG/886iWwBP38wQugYGDwyUTzlq+hYnVQtgoRHJHERz3DE9/Sx0G/BCbfgcdIUP4tfa0Dn4Uvij2vBZeDfxR7Thc7BuoIu14XPQLYDl7e51vOh63OwI9m4MPDhyHr633gd+GL90XLRUs65veV5om+tsswGKwmEUpA3CyWhDtq3Le6EUiOMg5LlOqrsLZa+YYsFqzYEhmsveJeq0iKrda0MNZQmaiqERpSO+vbQAE1KNtxxACwYgVVEQoFi0Sg3iAC2gojvj1JYKogm1G8LkwBEUmAgzccObup6bvugkz4Dm50w0R1pvYwtNYM2dFTieojAyPRr0EuHTp8pFOwYOmo9bnuK2tqsYUQS0tDOMoqC00cl1z3edGNAySqFmDXqJCOozC3dlTb9r+9HwOCenEqFg0UorHqJjUGhMvbvYKc2cFjtmrvCafuPGPvYXySJYKjtux2woSqXAJVltftAc6QclhcFMYiZUmlt83CdlYddwqM+zXHHP1fam561D+sY5hCPH4KbDHwNOgdbo+uFNDN/sw1j1oLLhKcQEH1+E0l0MLAc2JjwFyS2OnGRe6pKUivz7SuVLfkYP/Hj1d2GSmr6dcU0+EDjXkMndP/9w+p2ZwIlyYEcmAlFrpUKN/HkXASVduLVbk/nNxupw7Rs3iUP1E/m9QLXQGSdY3NXasKFHuYbUZsA3Xos8K92EsXbOFLQYWbMQPCPrBgeRGdo6m4N2A5uLLmrFyuqpn3ELnoM0XRHC2atiKFC6SRYR76C5CkiJrmXOngdMVHXgpkPhWqhG/gscSSS/1DLTlwioOUw7QLeJzkuZDG3noFsic1L1385Bk6ByUgxnyfhQJMOjRzjA2vpqnBEGiNaxOelmyTyls8DlpLl3E4Ca9PLsSgLSTE1IuAHi3Ux4VfGsoHCPV3jgYEgNJgsRFRywcYN5WmIaf8RwSjNrBrwgaXUe05y0B7ymW0f8MZJ+wjVgNQvRHSOrvlUqtYu9QWuVqkt39ipVGEDkQFFIaZomA1OEKloUxUq6qlseii8NzE9axwiQEZNDjCReFyqrkkaybWB+0m6Yosb0ESgebDUIN0H5yeKwm3bo6Zi/NCNLtID5SaN4oXO0Dy1cAcqplWZauZaA/CR1lwGhrMdQOrrvnCKFx71Gz3zMeNh61H4wfPqcPnMOUrSlYvpWYG1bp0051rFZG8NrK3Ftqc4j5fncJt264wsTlM6DbrawdUHvNFKtI/LztEGcQlTbSuGMLYXduUbbsqA5mGtg2GbCrlQ8+1vdjijK9CB7WBSUuD6sIT1LG3k9YZdGNXea3u6Pxc4JtPDKYXgYuZGkjo6DVh2Lh5s2YkKsMIY2ak00nhZJPak2E54evVWl14mTj9L7u+bBqg8pOWtpele0SNyPQniv7eFXLvENVsijhsBD5lv47beK6ZQY/SUTjiUlXN7VQaWS3k9Cziy0i0TndLNJ4kVeq0EzeBluIjIJ8Qc74DNWNEEZI/11aMVO3zifTFwmDu9JjAyINHkkhKWUs6m4CL+Ri1Yw8qnkT83aBvUqckguurdklV/mOxVZLMcrs5tSG2iod8RxIhVZqiV+iIx7Zivk0pA+RCXa+wqpNKQPUUmU5lAikkH5VQQK2VAA8pvOYlmxr/VEbKcvjWCdFfjSFhrgl8WkuAdM1UQZQcpWppgZF7LVTIq7jDW1RDeVqS8TssGGqhtJKm323kNPZNKOU0jeeOmmNrzRwuQnZzLaTYt7+olLsjIeatpI4l/RO75stX+03rJOOhAuRTPXcZ5heGLdbhZowpbjuGjURA6xytiLyann2cWUb/RSsv3ETaTtxjfptGQPUJHWClE0ulue1ugQAPD96zNJVbtJoyV7gIqsFUKKRediYFftkovfURqG2g/6Z7PmxQWVWv2j25tqpyGhWp2a2tYeheZwIe/61sQiAv7CHnt9UUnOqHMwhqEMDpZR7D6hzZNH8IKTov8qYtkB1csSgsQbF3hw1mjhRLK5sQC6Gf2RxcBcW17q+shrRQWnTohOVraFJEhn0hTbjY4zVw2DlugBFkXJkk+iJrmTA1pgA7ESS7RFD7BQYYmW5E4OSBJ2QpZNgRbcbQU8Y6+3j/LN0QnByUpJHnUhdHLyXxzw9OimdB8ik1UPxiAvFVZiyB7KM2eLJKho8bsAOhkBK5JOoibT6BpCtYZEu9Snl6hqNL1wO3ZXrSKJIIxSUqdJdsDzwn0YeyNX/CjAprhOVDjjfXITOF0aHXSCwqUF8mdFmO4oT6kGUzdwwPMCYUzliYGMprxOmo2fzR9N+ltgP4YIyXy7eLuobhyh10Xz46k9o/TBVQGOSXYa+i7vKYYtMk/Bi55Nl4L6J0prl3dm0IeWS+GZrYfJmdjRxD5clsheEm4tCXhOTVjUHlFcaDdJuX25ewgNiu+3EAgy3qa1zyqFmH4wK0kA97Swt6iVgoaWSGTlOl9ew/lVzN869gFWggYAPZjRMvAKOUP6CSzD9evHWm8bXjQcXOXsrw98S59M4sVR9gHxXDVgMo2aIK4COR2wEsRTICXgFXJElr1axeXiZnm97OsfL8KYDiBCfXEd2F7GCFXVnJDjQoFW8Vz+WG9N9TFVA/ExckijLbV3a4N8jkLT8rs0cHKoCe2lkP6Blo9TWDNk4Tclcui/tccNZjp1zwX2Q+PFK+5j78PINXm9wH6UmVbsP30nC7khUIL75P3qdnkmrYbBZneCopgLlbu5xF4jh+iiH5t3M3oYuSZPfDd9iaH6jQUBUHBqlzv2bDdnAmc0Jcrf3+Q4KEPO9Zhu4A544vJ4gtSEmQH8c5SdCh/DmrCi+2LJV+M50UIaU0pZmjQOQTflS2gX3BCOKIDlT8/KQtKkLCyEFPlXFzroI5d/a8bpuJHPEIlCsJoCVKo6peCU1It905pQIfupIFEIllBsScz/6YWWyMG1alKRIXLKQXNTKofvIPr8EcQB4L1ZRYBGJVdNwa1rO6XY5OQrf8e6VDEbSqdRyZVReLvuNB1TgEtZ0wpOzxWkHEXYHXc7KCcXlnRFRblSWpIG5bpOXbCANeXyoCXLH0AC34mf+oaPjLVy8awCdujwulY2TYP51RfBSlESKjbj3nLh02lP1cXRExRkXkQ9WPTQx7JAucDMLQhAPHKwzNK0Jm8YfGxDxQLuuIiYCZpfji4RupI4TMALR06hWdiFsBGe9EOdG3WFOo5r5rnB48iersYe9Sr90jmtKItHIUzcip677rci/ABDXNy8xSto1jTKUJzBEKmiH6FVE9uBgGM2mz8mBK0vUhPlTk2KVKfqQu64aojY4a6rktKzGZB/NbGppTC7GtppDrHIy7Z7lz3dubFjRlacvvQVjE0MQJyGA0c88aojo+rwrPF1LokKFDakqlHTyChok/XQYr2vIbvVKnHdPde1rEtpUeCLru0OKVIsttLyGUGBmHT8KAyFumlhQiUCl315WmUyWxwqXVEYp9baY+dM48uPFxc80fXP729Qo/yBJ040ApdTXomyRqGNAckaBROjgOGIMIk+9S075j1zPpVWiaUkqOQN8G8snqs1dsCKzLdqsiInYVQY00Jxsbo5nrZF3LdpUMcc2ejydmpxgJmdoSAUSljUhQ/wcEAUA+T+6JB4t/jkk5ArBzerbqgBjuAJ+fFuoVKRGmY0wACfD1AM2gZTwqUufICHqJMPNwe2108LH8Ik1hbkV7AqYdKGGOIUZSQgpcixL0FOLQgOTvvYiiJ0T60qRnWAAT5Fg6yES134EI84/G/YEqixSV34AI/fM5CpMUYpeYBBAvxop6YGVaKHOKALYU08DFGTIzTAAJ8l+vxGHR1K/qB18JahwqauhTDACPkYKiFSCB7CR6v2arKmEs09x2QNrWQOYutCe5fjGmMJmQxowb0sRN0tB9FZfpcdDalM2FJi/x5Vo+rIxG9J7vdzhDVHbqaXEvtxSX2RClyKlLHDDLbDMYzxzvaTC/aDy2BXHz9e3Q9N8shX5v1qNckuhLpRsTOIYKMpf6gvwx9PaisHiPB0qBVjhUQK+WNXr4SWbKnjVPU5fhQt7Cji0tO30hRqhIKGWwmoDqAZeFUZTuljoxRntKF8yw1kYlXyGGAo8NJ3MtFqAhlw5zA9OpQB0/yVOygChQqeLT/y4LvKIYCEEqvotGEGudys0Y2r4+wgzKgCY/C6KxJd7KyA391HnBMLiIMPbqKUGaoTrY/ZVYDcHHjH0RNI1YB4+GgwUwOqj9MNCV2s3kY1IB4+GmzUgOrjdJeH21JvpDoSD6NfTnUYikbjYnamldnZMLMl7IdgfqvPxBoQB5+PQjvU02l9pPew+62lIRMbUBycLrIkRffhamNWB+Tgd5k7nukj2EBkMHwP5X7Lez6MooM8QrBnSBahRVejktUNNFLzDqhOrV7g4GkV/ozCI0iBa8jrB5SlISWRAXrx8/Xdp3C75T/aPYDpEWEGJZgBvQLP6W3gvRRfSVK6IMAUz6CxxMX/QuSOUQYDujbRUoeAJyjfC92ltQSj07hDhkb17c33ZOg43tD4Ilk4i3/xQssxaJlDsBPU7QHuq1x3uZVugB/GIyefdBFny2VNtF8SFAsYBcfL1on0LoMlnsHC4r74igKur9j4cPaaegl8F4XIGLEVvxhW/YKrJmYSnMKECe9KrjByXX4H/j52U5X4pXwG/jrv3JSAV8JZyO4WRUxRhFwKZyDbtirYXDIL04123Mv1wrCl8E5kvGWuFL5EYHHI4+nia49VsaAxWDzS2HTiNW8wEGEKNfEMdGA7O0XIhWg2amKpgyWymbiqylsumY1p2ln8pKwjaQKwGARpHEa8AcaF4SvpDOzdo7NRBFyIZqH6lq2yUjXks3YkeC8CEgX2nQ5EHHBZCWQumYX5aCffqEItZLNw86GcKuiaeNa4dGedffOtIuxKOBv5m1PeUwUjkHPhDOTnb17/oAi3EN2Biu6ttZSNRCkEZuvNG4OkBzufcpAvzGImlCcoiKVu8GLHLxGJVZLjshmZMvrscaTMnj4dvpTRq48l1t3rx3EoYZg7hleBzGAVuhI6iRGcclxmez4Loeixk4+kGcIoUn1zh+hR0vx8FLO+uXv0KGnmPopZ36y+6Fbx3Rnz8KMZdPc5vL57cgnWwTu4YQubdjJPe9ZiwBqlpFB6FhWHqO+Xp8/wH8V08+vQ3P3zD6ffGe/vL9++efP9ebnoiNdAO3l1rH5eILXDu/NPK2gD/EPuSvevmGsfEoPY/dX55c3VwndkuR/VBOZwjZsxC9x8Hw2iQvbAazzBdxBehH4EU6zxvThoKS12UB5Y714v0P+dvz57hR69fn1WPfoWJkaZS6f17WxhwQH4fuMvYJ5uoZ3809NTf5uu0Xn1NAw9e2e5AZ0OvkucR/opzPAFMfoCvl1gL/gFLBkgfofjfC/MH9589/qHb7/54XUV8tsPHeC9c0Bix26EDPHnH432M+IC1zAYfPYjPvsA7BT+fXR8tLy+uft0fXG9+s1crr5cXt+aN7eXXz5dLY/eHf3n36GlMteD1ezqGfteJw9H7/7zv47RbUB++ARgtrzbWF4CjssPyVFg/B1exYLY5aGlatPmuHx3v7oyL0m0OORp1nhXuQyaKGnzJT7lTY53O2CdbfM7U5sfRW7AfI5igbMvWmV/k8bEt6PxFl9HnwdleLK8jJz2aXyCa765ztIUVup1GrzuYkN/eMr1YY965DsPOP0fkFMXifsH6PyuimZUfYGKACxwGToP/O7h6Me8SL27ucEPXz37XpC8y5/+9PCALkJIo3eGsd/vi+IOS76RJGhPHH20ACgr0Zev8pKEk6VxRh66Dv6d2QuCu8C7RovMzgtV2WYstraNU0SO3xDx5wdcIfApAtTMJLB2owaIAC3+Df3bQB+VNaRQ58/YJDktqDCS+I/jqZXDytIQssY14KK8yiu3f/GSRPlArai5DC8WntN4S4KMk5SmbaWWF24pASjOOj4asLMCxyNr3n2vW6nLeHjki6QtoPVFtwwcENLFy84268NG6a6+a0F2fNchD9WCQWHNjw6rjK+Aj3po8BWW8rbv7nG3r+4xa1OZfrgrHxU+Jsd1T5njtr/HMe1zctw/hjpueW8cd205H1Mb/sdsh1/G49IT9rjL05T1gpLVcIVkvaC+r/spsp4XnoLMd2ftdw0XMNaLHfNx3TGL8brhFsV4X3OFO24MOo9Zvh/0Q5KK6cRyXG6pH9fOCBxTm97H1Cb0cX1T+Li+T3tcbp0e1zc0j1t7jMeMHb/j5u7bcbncd1xfZjturG0dV3tmx7WNrONyc+mY3vI5buzAHNfWo45bd84Ixp0fJSAPnD4qbS3gvGj6Wuh0waSN2OeCaZtx6ocT98QiF01cCyfOmzSP8tOM6t2XuOv+FYE0ZcAM/jT5JT/8CVi38wikHpGmuPmGP0V51YpAkvK2FJE0cdXj8aUZvEuIQ1LrfhL+NOWVHwJJyltJuNMM3uDSJ6k7iudwqlaUSsEk9Wiaokm3jW5WKGkeYHJEsio4pGjiIrojZ7qO4ICcqYejMooKKsIq9qdjRNMTSsCfqYyogn0JBC8DEBXVc0MCj6i+SPNT0hdB4oVkMG4LmJK+CPTPI2Mo1vMoGXScZkEhzBDeo2SwQm9zCeqL5T5aQBWFXUAEOyb/aAFVNH2GiPGxB2UI6x63jok2KSSGEbRjTHo65MYYGay4XlPkUGFrpojqHXuPCjY3RU53eLgpUunQblNk9YzQJwQ0myStFYpsqrR6GLEpsuphwCbJqYXxmiKnjMQ1RUgVS2uSFCoO1jRZVNCoKcKKwE+TZJShm8ZI6ZnqTYz4KldiGax1kth2PNQx4soQSWMSt+IbjRFSBikalbgMNMSTmiMKjgQxRVQfWaIIq8Jh/JhyED+uh5A5Lry3j0sXvePSvfq4cJI7bninHdd8oY8b3mHHDY+s46bv8jHDKeq47mB8XPf5PW7Enjnuc7Q5Zp+eg4/3bgLsMAiAnb7BRn2zeLN4bZRbnImBN+QLJxU03I4Tl+zS51acIoLpDDBCIBx+byM3nMoLTfHObAlSor0vQUoiRSOY83E6SSk0waly3eYUQS0rOw4eP1rUKqmoHDIFQbXDTV/Gysj3fcZycAEA378+M+tjPGEZ0aTkIw2QT1WL1LxZSdaAyuKAfet8O8N7OIa9cyNMq2hweDnxSUX7fIKm4hPsWKmlRDDwmxsvEuU2dj4kyiUfSpaLmgzbjtSQxsLhDwViyXasfLlR0nT4kiw7hsPGTRbYCqTnS1tK2BNXICUFkIj2n2QXktwc+LVE0ahxdu9uvqAFhC35ywlT+CzyM9OK3ERie92F1cpt7CIqFxdhOABEeOXYTEJbgfx6fZArvRhlk9yXLLtesOSIrkYNxOzrTFYFrkYUlWSZnItl9ZrTbLhG3nMQy/ascn9sMhp2uy06qyxpeN1KlY+2z2CFc0M4/3OB5N4g9x7Os6MDaqrFnNhFHj/5RgD5lTusXJIfxaYD+WlenH+erJ84qJwBhzDu1ernWUDNm/OLeYDvfv5NP/CHmruCRtjrsxmMfHNxrR/08/nnS/2oy/MZVF3ezQD6ZXl+v5oD9v0soDOUJYiqqCnW0MVcKWvOPyor7soaR2UNIOy6zE/nn7//7u3ZuRoEZQ2aslz8cnlzrmaMiCWr4YwbUzWk1bXTytrivjOe06F2VuzsLXT+M39AzoNVGxbVGTHlmI35YY4pqxi0MD3gNJWED9RpiNAa6iE0WbpFIMYnYSyvxEOaWdmzGYMNiEEAC81TiB1spcxPB4Bt5IZrZpGDTtspxkJTY8uZvkTKAWPbrhYYdLidnE/UgRbrsd30rRMulOk7PxwwjqXFZmCTJVrqD0A77VqAgh06GeyYG9fXgacJZhs5vqUFKIm0NEHumZYC7p5pqa6uloY0jCx/+rYUB1C011Kofwdaitrvmoo0wiF+vDrQ4kD5IAvD6Gp4EscN5S3Q9gL5QEvxTvT0eInv6rGbnlqU6MLBHm76kMwdsJzKqVopYsN9WylSpql1QDjFqQYteIklwRWLA+jJkrck0AOzz+LpXicDOOXCg//WjJSWPrTM0VgBULjMUWyOo1msBhgyUdIAlLd/GpAaZwOUIuHWSBNO2RrpwMOtkSygOPSLhd9ywG/Zj67EASUDAj2yvUd57UIXhsTVpi4IeT1DB4LcdZkuEKlrMh0gMtdHOiDkro10gEThHgWMtZ6UZ4vMyXcHhNQZcQeGzPlpBwQ+f2fKOkHABSbHfXcIqhahQRmI1JF7D4b0UXsXlhclCephpAEVERuYgXpk73O1wMrRNPFsJfF2TDdIN2owG1uHbUxZg49uTCqykGzA3nAotSgkShBbsVOwormXstyBOHEH98ATOc6dn8GTN8lkyXcSyW0WCwSdaFAKEHkSywBLvmr+8ocoTJg4tEGShBAKBInELWQWWAy2Uhce2RgpTCtylHgUisTFRpZ8+CDSkSOooptorqq4TVHQnzNQ9ntH3mSuDlBM3XGrpaJtLw8teZ5a+VWrohJGVRdYLkLVqodSnFr1UIlTVQ+VKLh6yALIAnfjAgedSixGuOSVKXUhggFDBlqqwRqj2TqYbAMOrb8r0ZAHVNapbVHs2ntdujcym8afkuF7F120kySGtVujqReINxb8pua6N9XCAwiSQhwMoWA7qkQoo4QrkR4qtU70mJr+1p82NBnAQIdWVcpHQmFlMktHZXJLhkpEzwqKpQsJyzM8aDjGobqaUobSVQeA/FTwhWf4UL0GmOkrBR1AxaAFLa2ggue/Rcf5VTTGLKRQGRIKDdUM+KUSwiw+U4hFes11ph6jHqhYAUqz8kiBAXEchCTEDvpLTkUhQhuWIdKlUN64sY9b+CzaxhYKHtx8QOK0aYSSYrNdmKSodufPaxltBnZkotdydHJtPyruqYuqGw9kS5VilLxTwuMHwWhiPHKL3QfRUGsislFZwdRdWf02Y5apQDAuj2UDpADADVNUuh+BpGFnc4qW304lc2bRAEDO1yoLjmAAQn7B8g2yh7NWqeNGH9+jZviW58HWj4SZldR3kxaqYI4aK+ltSxti+i7+kHBcUbckQil1Z6McwLwvpw0mM09qEN06KQDMt4MhrB0DB23NWJ7c0tYCws1qHma0vN5lKlbc6iplys27M1gl1yjK1QZOdcA+jOWSb3RpUgSnuxhYDhyP5KNnJN/PvNQlLwSOLBc9ioGau3rTx13POiWwzCpBqHDv1C1r5GCgW6BYL9SUkw+Qc+uPy7+8wHVZn1do4XuxTpx8LEM8d0DqrLm16xbiwv99C+3+rSRZUNRUSQmsVwIOqV1SxMZ9XVJe+ItQh4hMYPm+9CUCKSokpk8uU611xhJFjai+HEKdQKo44QDRHDKlCxzR3nRJLVuealQn2lK0RJajHomizLWVuLZpgziFyqPrceBIIxSIRskPMWLIxC0cNtnoivMByTFIyM3SRk3fxLD2aL/aBegK9Or5Al+KMHTWalhkBMcoyKyP4AWLfAQDs4cekSha68YFngN7IixslKA/shhAu8GhjY9vrR0vyrbQz/HJsYUkiChsO0YCsKLRaf0XOKR8dFO62EyRNUUXVF9APMmgRMQkEnh4Xa9RkkRJIOVs0dMpRR71EXiDUkDALvU9Ywc8L4StmDfgnUYl88Lt0FCMShEVl50Prq1WCcN0h7tCB11vD4Xk6Z6/ef1D3qSiP1EbXh1qzJ+ktZ/4KhjTTvCU7L/gQz90Mg88HL17OPoRXbUFCby7ucEPXz37XpC8y5/+9PDwcLRL0+idYez3+wXJrwXsCww4N7sjHy0AWiRFX75aZy5svwKcLI0z8tB18O/MXhDcBdnYLTuUJf6JLzDFIYa2to3TRY7fEPTnh4fg1asfXRSFERkyeRVZKZqH468W/4b+baCPfjQopf6MTZGTg2ojif84/nv56OoZB3ZM4Kv/RPaJgR8+AQf+3MB+EVRpyRWF5XcHYccLvIGdy7iD87z3MLHzv/Yca8/8wAYslTDFNvlfQ4415FdfJB+OrCwNIWsDjjjtMrx5fEitaGYX6bVb97+Ojo+W1zd3n64vrle/mcvVl8vrW/Pu8mZ59O7ox79AEzw8vELObxDqp4ej08XrhyP4BAR2iBb04KMvqw8n3z8c/QViQtAcE34SWD74iaXrBcmCpqpIKEwbwfHAy9KG/4VJC1lHWDT8AP7/j5vQc0BcyScZ2vim+BLOWqrvqjvdTEQA9cLwZU4CwHwhFkYP8T3h6AkuVcScvbKLeX1+SuzJ8jIyz5WGUFxBe1F6OMkkT1ZkPeDUPKikyW8HGJVJveNyOCUQaRx6UoVHbqDC4lSsU1MTzDoNXmvCOVWFU53VU6kIuaMkcf8AKmCA77lr4vOA71qZiPGjQZrc+iOXBFG/s9Id/JnFLtIuzRw3fFf0OkbRMBNZZW+Ef71S07OsgI882oCsviUfOQx3LnQRdfGqsU0WzeBn5WCgMnk7H4QrQoWyU4GC+gPFijQhZGqBS3SMnpnL8GLhORJlox7tolxJlW38ckpt2lZqeeFWNgC5V73mn6BOuORC44b5pcdEvnTTt+Sr4u8Gbjq94I9tmctmTVvT3LtMNLp5Zi+9MVvr1qShqL2MrzvSEA+Hzu87UpFp4kCqzrSwjeRK2iHAtzOB5J22ioe05pe1c6ORsrpshCbyEwR2iC1vPJQgvA8CXaUoDaIAajQ7nfc0PhTNA/r+nfFL6GU+SIz7cuF666boDsNkhxfmUQXjOUY34ebIdhMq0Q6NuzFn073BQpa+jH5gbkFU10fdVqnF/DTodGvTWtH3e+pRi0aVrhfjVlQtmjFwlejWulFWm3Yt5Cn6Sais7T4pkNObtmxe3pSt3NblnRAFovQy1LxnXotCTUjpGjVPf2vRqAkpXaNafEAt6tTwlLRZ6MLhKgqAtkrUhFWjGcTTq1MOqLzf1KkUhatEt8aYXat2LWTp+kHp1dkpLXo1EFXoo7m5aCCq0MdKEkBcRnXpUyGqaitmqEsNVPlzovqkS5daNKh8rciJKL0NBA2qSCv/SV/320Ccbe4zLTG3/8kEmbIWNVtNTvCEHfrdMMYn4UtvKMX5T26aLWbB3SRmnw4zx93IJVlXS00s1YE8yTzchUGfit0Exmkqu2Kj0cxXUrGxo4f6eowsUlvNyjHl90xNR5lwjfYCIZ7tWeT4lCYtB3nM3mDpWr8jea28acCWL6MFFphf20hhbLLWjjMJOylt87V2+7vcZu3iZnm9VLENezmdbK/8a+ItoXYHlihhXqiejxdRSuv5bOCsMQgFI1fXaDFSuvNaoJ1/PijlCR0dml+tfj4kzXM6mjQ3b84vDkz7gpIuC9z9/NuhWSCnpMMCH/DNLgekf0lIh/bXZwdV+nM6OjS/ubg+JM1zOjo0/3z++fKQVC/46NB9eX5QuZ7T0aL53WFpfqdN8y/L8/vVIeleEtKj/fvD0v29Rs0Pqp0r+GjS/aAG9QWff0afUhUrZRK2bZjFg3naVVsJyRfX2yRmX6g8nBURqYsflGJXM0x2ryTMZik1Ps4wlvkoYcBCqTHD3EvC/IpSYoZplISpEqXE3c+/mZ/OP3//3duzc93a0NgS1ZphsiNhQkMrob+uy6/qXy5vtBesAlOmGnPMpKTMllqKaJ8USZj4sAqVut3m7kI1dWeZVah061GAHoIrR3V7vNx9T2Xb7Yiw7T2qPI5R5Fplm+rW4hq6Es9XBACKSxvn0a+EV+Paa9mPeYhI/erVwJXlnh2rPN8wVDZjdYccsHyVXuZDuqnzN8fFfpMlKl2Yh2pdAa9MwY3rz6deDq5MuW3k+NZ86pXwyhSs3Ts+m5ZNDupU3c9YUHNwZcr9nkTufNoV6MrUi+fq2mvgypRLrbUHTPUHaAfUbNFQrLDqI0tc6qo7wlTiFBfxzqRmAa9MwWzWLjJT3UMiAHMfW1E0ZzbSLNSp60UJuqTgcUZd6xS+Nlf0wrjUwgXMNjfagdjyco3HOpl3yFdyzsX2QvvRzCInvydBcXFo2wifCaFZqAmKEKsMTDOgYY2AEuXI0sus6pUUVAVKiNOZM7DioERF3I+rDKXGoWLFQYmKuCufVcGCgTL1yi58djXrTNSom1jkOp0Z9SwozO6Mo2Mbo9FPqh+8MeyOBnE0C2W99Wwa1ggo7K1nVU/dXo2VPZsx2IAYBDYwn0IvVX8KfkDhXkpKcthyZi6+OQFFgdN0LET21U1b3VokYmiRQNrz6tjgoUZVHXtyfSqq25ezUx37/L26qdvqd6yZG5ecgJq+UdNual/fqHRHFQQ7dEOBo2lbtU9PiokSdWfXUqVyujaPe9RTu4G81bPp2Kefyo1H92zmljQnoEi5mfvAnIAa5WYenrnqhmVhZPkq4wdyaFdSUOPJp8VNo0c9la4av4OZG8ycgBrlZu8OlPqhIOHodpF05sWZJg81G8Fa3G16dFTqcjP/sCxWOixLHDfUEf+lR8GSgiIFfTBzJ1FSUKPg3AvAiUJX/cR35y6dOQM16s3dCarsA5P5tVOqHtnDn1fBkoNCFc0dsBy0l38Aqta5qHSdmFXVioM614lZFVTqh6nZB3NATeV+mMRvYV49CwpKFHyynHnVywkoUW6fxTrc2nu0KxioCxPuvzWjGVvUNo9/EjfhLIBGAg66sPQr8A8us4HkjanJzbRmpGbQeIrG/wivL6by6itmPQ8aNZKioaIJml1TiToeYNvzVR5VKMtfjb3m5qjDEbWP2f+sFoo2gL66OzSMYDBTN3Y6MN31KKz+csQxeku6QPGAGvGdFTt7KwZqmu51lqYTb2jqkCynU+gvh4S9hh6BzgSDIDe7g4qNhJonLXasmh6BK1/UNw1d+dJoFyo2B5EvKrp5Dzhfax2G1OeowBC2WXtzHgdRRDqyQ0fVRWaYod6i7GhU2pzHQWTHAY0GEhAjy8odBARP/puvtfkg4z1zgy6kMd0g3WhoTPJMMJDdmo0Ik420ePIdJkA0zB0cFWPYWfVvUzmICtxRPhW2p9gQDthYmc7zcI2MQc1pBw3VJbJdDWbQvZ/NQZRLFUPBxAMgwpvTX2GTXnLHjQjJPm2hIIoSVLEoG7d+XgdRljoyTOmY0aUso7Ga1zKJVHYWl4PImEMaPb4kKfA98AS8rySK8zrUMR2p2aXccs+R1ZzoTLQFkWOpVodXc1on8rOZdCug1Zxk8bQ0cQy1cmQ1Ws2WWUrzSmccXKZy6oPgRnEIuSchhAFBoiWEAVNTBg01Bz3AVpM3NkvNGroi7VLIzdWycM7Wr4avRkMtrthM3RQ6YEOwaN4KSDFQ5nONt2BnG5FRDNQ46moMlsrSUVqk1E4N93tHhycyS7kC+tCcZJT4L5WDUQ0LFzVbF5HyCmhl4+B51MqRVY8YZ1KuQUBZDzyPckpDqdb6v3m0oxgo74Fn0rLJQHEPPI+ODXx1PfA8yhXQX6tvXNOWtSvpFNuyFtde3HjCOosnoEc0ezcGHpySCw9rWpJ84Ifxy8jhEZVhvuV5oW2us80GKIt8XahuEOZGG1R5/nWYEsRxEI62pOQxa9fWLSapOmswSNNzoMQ9hMsup25nUMYluqmZc1E2RVOtEk6rKWXVElgiApAeejWBFJErAYgDtB+cWraq4UqZv8QulLsNk4XEe28JqInHRanruemLXjUZ4PK1I7ZEdtzGFlr/NHdW4HjKYvr36NpLRa7mVQmyY+CghV/LU94ndxViisI/YR/AKMyKO4Tc1rkrFANcZ03SrmsvFUWaz6TlV9vVu7YfyZlZ5OaI0J3NipswRNqg8EZav1sHxQWppcOIEiSrEGzc2MdHAbII1lRnrGs7ZUxKKm4BVJcMWhP6QUlCSnFhCldcbvg0nLEwjR/u9wdhUD4uage9kNmu6By/E02kDNo73cstz1vDyY65ieGbfRirn3w1Dnkw4ecq8ukuBpYDG3FZBd8tIvFkXuoS6cqO6JUGLrUwegjMZeJdmKSmb2fSFiWQelInF+7++YfT78wktM3AjkxEWHWOFUbJn3dR+CoHptZuTdZVNtbos3aql6JQC4sOI8AsQEGzYFOkOscbVim3lNoc5M6uIs9KN2E8g3YUuBq1zILArPo1WKhYZ1pn8yjYQJeqGOqlyiZvDt1aBCSqR1fs8AAal1BBLSTFgxyGmK94lvj/hOue+d126iIFdRi4dq+ejHhAjDM8VmqZ6UsEVEXNHFCsiS9bOTIFnUexEluyUv7beRQiuJKVCWcqdqGK4hY9wqnE1lfllzygUh1dsmJZMlctKpAlK7R3E4A65DKASwLSTNXtVQMqdnORrbRnBUUUAaWxHIYUZvJQoawDNm4wV89GM1A4bNeuH4OAIvVUHjDmVFDKIWNGtGDMaA7VatBf5brW+LF9/56C6u3KoLWnMD4HuvYUwgCyC5TdI00rw0CVrRDalsPmctW35JRWNLRc1fTMThhB0OWrglfRy2ZGq0ptaLmquWGKurhHoHxY31CrCStXJXxHox16eub9zYDWLWi5qqErKOdpA1vIkhVLrTTTrFEJKVcV/aVOemHDdPQM4HJFKMRDOrzD9enAR0OvxwUQbYcIBSlydDB9K7C2nKHlJu6Ast3j1lbi2pJdlsvQgU0l647ZTFj+stSnC2zZ0VutitQx5WhhgziFjGwrBbD9gwNArfnCAp+olxb+vDxFGpWp3iZ9Ds4KbUK8SCgw1bYRmxCzLSNz1NRlnZrL98ihEpu7E2hinQNN5etG0gZBHKTraFOZa6QtjTPG10i8iTe1/dZBmZenjJFeRxO2Tpx8vjtuUDapCYQmcNYSLV0pQ8JXF+JHlwUowSWnJJWyrGFMpfotlPOtcrIlyvhaBmdZtsxaRhGt5I+nKGv1qYviiGUmmuKLzLaV5vcyrSHNpFxr1kEu47+kbI558jq04qE7dRhDbbQQMcPkmAQshowljNCxnHJNJS6iIefCD3pEXjGdXmwbZqiCQufCR9epUkq+g5/Fsk5udRNuQ00ZW+Fr9pRZuQUwhap7Zitl2pA/hWi095USbcifQjRRnPeJrKwntzOo5UpBHGpXVmwdifZmyA7zLPTiHFByyq+wBX5ZLMT1wB3+4hwiL98wxWpcIf2gu/2eLJxe85uGqW8qseGmNFpErMT1xB7yspYRsTTpbgzdxKe4LXSwl7XE1U1ayqIWrosKWR5yH0a8XoXnY5z9UNvW8k7LE+ZFV8N9Jn7cYiBvM9pW2HIcF80OSCAxOR4Tuep5EWMicJW3FlnbT9xEovdhk2hL+kiSEttxiqBo282YGQEAvn99Jq3paxJsSR9JUt5uD8VPcGOnu32QzYy71I1tX7tf0G1JXCjQ2aK0W+lqH35oFYwyqbVHMZddaJH6Zv4iAv7Cjkcv4ZYqGHVmxjDYgO07uUex+4ScEB7BCxaH/quMeweYMHcIHG9c4DlwRIsFyWfMghDj+UcWA3NteanrI+9iNUw7QYS42haSqoBfU7AYJ1xkVPFqCR/BrSjFKqjVZAsxQ1sXIFZktbbwEdzUWK0lW4gZko6PH8onRosWsxhevau3/CpM1wkygauiXO7CEGLqvzjg6dFN6Z5ULtcelFFs1ViUIX1MrjtbJFVNH9cFIcQTWJECajWpXWxElw12qT+87N1QzQu3431FKsUQsFHKEjLuDnheuA9jb/S+BUWjKVCISxSHT24CJ+0TgpJSbGiRsrI6THeDfumUdm7ggOcFYjVdNwxvNCUKq8Z4wXpEq74F9mOI+JhvF28XbxhGaO8J5YGfBOZ2o1bgJixIpaHvNk9oJ2nmuOE7A1m+UIBeZCpTjZvXr91UFDJPMmUlK0zOWEFyOMBZ6UcxcWuiwHNqwnL+iG48dZOUOmo5zGpQ1jhbgSDzRe1TpBmHaCUJiIULRJVq7MLhqJIwLf/hFD2mG3kO1CrVSFQPFgph0CLRWE1b69tcmvKtWY9buB+9U9Ff12xOHYuIcgOyJtUiMS61VJPKsyBqlWpKeRYFLRKpWfLtKHIXN8vrpWh/fhHGfAFRWymvA9vLhMK708tEuGyilXOXvlGCaWOsn4EIGzm20RYxej+WiEKXw9Hee2JkahJGc0n/QFtCKayyo4g0k0+0yNbmGLN1WiNPPZ4DXralAr1xU6glHs3AjzLTiv2n70ZRaKSe+WDJ/ep2eTZrXYf9EK8VMVmqMOXJR2dlmJipaz+Oo1BLrNp3aomnoOONDamiu0Jd6g6zQVUJrtFMfqgOJCPPvZPAAaYbuCOPV011hawRMAP453AWFectaimLgQZL2KF79rU4D1ZHlgEa8buawmZuZt0QjjmB1b0So7R4Fej8xapIUZSpuoRJvvq5HDNOOQbQQ2wKKYdeukvrcZfqUuPCl6UmQZr9J7MppMxcucgd2PNULYKN2xr+8kwSlRPDpoiJ5yGQqEcQB8CbyKcScujVq25A7jKd61yd8qiLkJcH0/hUQuauYh4AEY70OVM1K/EFSnWZplqCqUuZkMluTRS6vkAgm2lSLFEHX+EqO45RvFzgrUuRlBsTCNFiDnWSA3wnfhKd4nBt7KkoLsAOHTCcK1ip+mJ8mW7mli948ll7rarNhmBReGwr8zg6NWI9lIaEf6ASj49WAQWNQp+Mam5BAGKeiSBL91riaSy42nYWA4GWvBfd3HhWshvNoUo+jYkX8iyRsUgUKZWfsZwywqhXmCL2vucGjzzDjZrSqEfvFyUhF0YRKlKqzgXPXY/PBZgYk724eYv3CCwBTWFag5H+cPvwYUvJ2j6G8wibDtXYYU5kRVRmakkO6ABbwYqjHUKK4FFElWTEVm+eWqQvooD5eyL1R33QqSN+T7B058aOGVlx+iJaTjcxAHEajgyRg7d1hBqRqTslzLyvdpe66g2yp1Ezk1HoTXamip2ThiCB9l84JPH0/TmmIQqtejfqhmxRbJjRwoQDNXdw86Mw7B6pCbMrxSnJrykdLFkRmlI9ojBOrbU3plxQkj5eXMi6Nvf8/gZ12x9kXkqIFB1ReYmFjcJMBtTSKOgZhUyJd90gkb5lx+GI4jvItRT8Vd5kcwP8G0vWnec7YEXmWwkFImdlVAIPKdx8hyldOZ3BgL/2oBFzGoaYB3cPIVi8MxTrcjqluqSJpBwQxQAdd3HIDWc4IkK3Lyo3xW65EwmDJ3Q4bAstEEmgSUubSO4DhEG+KNOJ1SVNJNXr0cxNSMTFuYeMD5LE2gJznW02PUvg3LTa8qYSjDJyt0070sM4gi15EgjuYyuKQCyJXl3aRHJFzzOdWF3SVFJx+N+wEZJgrbqkiaR+z0AmwUylmIl0EuBHOwn1sZIzlVCKIpnhQaGEjKOlTSS3ROJuJHGjhE22G3Z3kdW+tsRNpIeOcExnVUiZSgbtn0rIwUqO0kUT9mhy9CyhLmH0Yn9jADWaCi1lNJ3e0y6DNPiOvfTAk9Z4NH6ZfLyHQaO6jibSEjP+KAisqRMKRpl8PAFSN8czKNPP7dcEtuMvOsM+Wk8u2E9arb76+PHqfuq8nEgx71cr/kwhuhuVGgaRYjSFTe3VsTD+7mCAlYxxRqWeLFaFsPmWiyVuHzGDETRXgaJoYUcRZzQF30pTaDt0YaOVgCo0hIH3xqw0jI1SoNEN6ltuIBe1ktgDi4IkfycXtyayB/gcykHHkWHavwoEmKPwwbPlRx58V/m/kfDmFbE2EDermzVwxttGmFsF18Pwrkh8sbMC2gVXLjsWlAAz3MAqNF4nHg/HqwA54PHfvz2BXg1KhJkW0zXAeNjdkOvDdNitBiXCTIvdGmA87O7ygNU6DFfHEuH2y6ke49F4QhzPNHM84+e4hL0fLBU6srgGJcDsI8PRRy3Bj2z/oCELasniBpgAu4ssSUNfK8c6pADTy9xHWifVBmYP1/dQ/rdvxxZF5MWHvfmyCC36G5W0YcjR1ugAHdT0BQ7yVuHPKKiaJOCGRD5oeVpTMnvgL36+vvsUbrcigfcG0D0izqBE95BYgef0NvBeiq+lGaKgwgToIbTEVegCX2c2xSx0naTl8lKYZJBeEkOWkJIlNAPebEC19833ZAA8JRsSkGaRGVkvXmg5Bi2Vl8AkE/RQ4Kmid7kFb4AfxqOn4nT1YEvuW4p4SdBtRCjQerZOFHRaLIAePhZoLgELUKivrflwVp96CXwXhchAsRW/GLnsPvQkOIUCEqCOQx1hgMk+dlO1TEqEHibrvMNVRKMS38fB3aJwjMo4lOJ7ONi2OgK57D50N9pRG0VSCZTiBzlgLxTFREqMPjb5XTYm2vhRx4dG6WOUxqYTr7fqyNQAengA29kp41AI78dPLJUEiPReBupKaC67H920s/hJYVfWhOjjEqRxGPFfRyZMpJLfw2L36GyUUSiE9+H7lq22ajYQ+nac+C/aFqXgt67Zpt3rgLoeLJfdh/5oJ9+owy+k9zHIh6bqSNQA+sbcO+vsm2+VsajE93P45vRMJYdcfA+H529e/6CMQSF8AN+0Y2ApHGVTGL29hi2DRT7tIl+YxbwwT1BQTN3gxY5fIhLfL0fu52bKGVOMo2dyjDngR3JGHWMpDo9K4jiUMoQfw7DA7uEXulI6pxHscuTe3mMmalErxkGLmbQZ0Sh6PHOl6FHaqsYojjwrHtGjtPWOURx51kKKDh7ftjkXU5rDcA+XzkS1Dj/AElvftJO52scWh76xUwpRsqiIxHK/PH2G/ygnjly8nuG/988/nH5nvL+/fPvmzffn5dIvXpPuZDawGn2BDBHenX9aQavgH7J3KH7FrPuweijeX51f3lwtfEeew1xNZAM4PypwZ6U7SVByAYqFdjVS6YyTi4KDzUgW2FXU5AOVx51lCv7jjz/MvKQAB/msnhRR9WSi1NuYwCMXpJB5ihKlmnBuqAlKsNnHEYNUcWFNBjWhKbEztdGovBrPVEoG+tjpRab7Ovcihug6ccwktB+BWjgS0L7cpcV6+3ZmOLGLbpbJQwyRX/nlDZfkx7WU8iWJmY2dHg6Ci/KSEYB0H8bodCz2g521eMShX2TBHDRQHDTD3rmRUvR1aMVOAT6ntSMQ431RyzOLR/NZfZ4al2MXsXxny4osgImAY1qRexA8DqRoFNg7WGP2VgxKMussTWfOsrL9zIPIaiWyd9EgJEnQCmwQzgfv2j49x9aEvHFjHxeJLNrG1owDh1bZ9OCUa74MmQs48cxghsFliW/t1qYbwNH2xkL3wBxAw9AM2z8fHXwS2ANPJGKFMh5RfswGv5SPVF1tboM4hU9RdLGpE7req+FVyc5vhleUDUKDmYF7hsdKaN8kOU1S4yrDsaI6rmEbK46+BmK8nDwQs6AAzkix0qQ2Y97IFsuMCzo1p+uXgU3LZoEx3qjgDFM1ra5kmiypr9PCAbQuy3iOD43NHnP523J1BXPu9vOH64/ml+WVuby9+OvVaskr5fLq/ZeP5tWHG94EN++vLleflgXkh+tPV3gr58nyMvT+4eH//J6F6f/NV95O0NT+pFyqPbGL8zX5Z7ywt3er65vr/3dlrq4//3Zx/9vdyjxfcpNeXn86f7807+5vf7leXt9+Rn+tbi9uP5m/nDbYn3JL/GQWlkBWL1mNllZxu/j5/PPnq0/m1efz95+uLsdJrMx0dw8Nt7r+5Yq7TCyvf/0Is+7m9PT05uPq/Tm/Ftfm8hrv2IwzQp78/etpAv5m3lx8yc1nfvh0vvzZfH++vLo0r/52dfFlBW0sQ/7F7c0NzC0i/+b28kqOUFyr7s8vr2/N97fn95eYuvkLaq+UiIeSz0YXWiLi8/lNU3lStYs1d7GKXkq9v/qFIfT89ZmwvM9XK5Rbd7efrz6vzOvPF5++XKJ6xSfANJer89X1BUz46fpzU1EcfMSGD9zAcwO6h+7jRPKEaHr9+XrFnfT+/AYXiQaP18+v7S+fhGQsYWNKyTjb2K9fC4hhVbfru5sv5vndNX9jU9gCV30TUbspe7RxBTPv0zChKRK+nN+PbM9zYxAxsG34MpYIaV3uzj9e5RkmmjW3Hz58uj2/RHXg19v7v6KyfPFX/o6gvf3OgZlrfytQBuol6frz6ur+w/kFt7arc2jpKzgY+oT+XW+XR/Rc/Jb5m3n36Xz14fb+ZmT7SYr9b8v71QXspa+WsHUa3RIT3eEYqTWw7WnYfr06/2sD0TStNI3ddZYC0/zTn/bAevzXfxVg8ev1h+sJTS1Pj/L69ZnsHuVbMXlkCPv5C2xDL/9qrn5G/kfmp9uLc5gLq9t7VFfvbnEhXjbgzgQIVza8OF+df7r9WBUQPhn3qxUemOJBcr2V5yZRhq4zl1cXrUETMVn1EdOEubfEh4YH2NampzjMz4IQTrB4PkxSx/73f+/9km+uyXFJGJsBlz4+9VEaht5tlNsc/bh24FfV00VmL9ASExQSY8uH+HHPVwv0he/+geOhNTLLAeuM3udTgG8/P5voiKVjxU4DH+ZPq2nlwUe/7J3lBv0Eys8WdpQ1gcM4Bc8n/lsd4BsKfBM9vT1J6K0aNdBeaKWmtXabo9Nwk27G4JMbCfvB81sLyX+WduxGaQP8X1DgdmCnhpWl4RYEBvkSLbCay/Bi4dHumgoK5CYLbPTQTAD+b9JgmMYZPWJXwMGxUksqvkDmBFYQmrYJ26M5NA99NzU3MWz+zCjE20QzkIAGAM82iObKfogfp6mrOeMLP9QbK8K9kH697Y6e4Icf1GPvrThwg22ysDxvBtVLePCcxtacBCLgWAFaoGh0S5aX6CSBtunxmbVkJA3fegSo24CS/AUalKVWvAUpzaPjs9aY4MSHT34SGxlMpJDuMn9NkcifqQenhyUnPnzyUz44OXFOv9VCgjlAgVTQ8xP4/CeBwUoLpGp1BvlUn3Y1USdwQvETbzvVIz8/dMNHBkW47ho9E0LcQ2jJlFgd2MkmCE/I01kIdfTomFb9nb6yVLR2Jt3lnPyKn+g1k1o2o+zS7gtPfs2fzWQbZYxE7NM5ZT+55ZuwS7SMSi4iNumeMZ1s0LuT6p1eA2kjJmKt/jnuyaZ4P5vVtBMUqn/9c9STDfrgBH9wUn6guVrqosieX3Z81r3wM229ZyIrvOLRWu84gSNdYCc/obcL/KcOLsUk3CS/Td+Kmqz+lst7eHUCJ+o//cufbr+s7r6szMvr+381/uVPd/e3/3F1sUJ7If+6wImnFLwWazexGfcKYbGf3CQtRVe9IxxdZUGWAOckslBxa5W0QRF9U6/BxAOZOJie7sSMyoICdt2FSfo/y7BihoJmWRC/6IXrAPjnmzNiLiddkONuzjpzPQevXi+2QbaotXcohChtz5pA6mvy0QIZfIEdfNFlcv9Uph9Mz7yBq+f7TX5574kHgm26+4neDlSd1WgOJ5LZ9e//N7vnzW6yf4qzOt/boXMvd/MOo+b8IXH32x9Ov/NPT0/9bboeOcHq6HyFW9sM/jCjGA6UNiZefhK06a/e8cnJ1u4YrvIlh8UQzUNP4v0zlLP10SkCub2TJmup7xvywRRXz4C+LZoJz9l41jaZoWzIztxxzayA3fKvC8v9s9it1YKgaCn+WsqQ7Rn+KMWd7N10d9KOfHQgdUNUnO3GduZZsQMiEDggsF/G7WEdjkYBbBWd1qyQfwdqSg2UoEZVmwWy5kcj76Txr1c//uXZ99CnIEYxreDHpwviZg/QTRdusIWPvqw+nHz/cPQXIqDo5EsXpsxe+KGTwRqFb8xYXOCDWHfkszto4/eYeBkua4FdvWB6KCkCcfqytOF/oaBy+FA3fQQFYM2XKYj+DOk3fmtSySHXLy1BmuLNSwFdDHWspphYIa3MzomNzXL6tuN86YjVFDejyC3s2Dbzo0R2TBBRWYGZVlYD+KgMx8Vutuo32TbL1tHx0fL65u7T9cX16jdzufqCzkvc3d/eXd2vrq+WR++O/v5wVAsL9+4BPniAI13rCcDyGtqPv1ixiw7XJejxO/Qv9AH6B7YAkQu/ch4/hTZZbM9fvCv+2AL7MUSHTM23i7eLN8Xj4+IPdLDtNmqnaw208+f/IP+CAo7y+8W+Gsr/gFlB0JEjSwIt/5//dfSP/w/gUKCT=END_SIMPLICITY_STUDIO_METADATA
