set(SDK_PATH "/Volumes/Resources/git/matter/release/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.2")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/syscalls_stubs.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/../../mbedtls/repo/library/aes.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1parse.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1write.c"
    "${SDK_PATH}/../../mbedtls/repo/library/base64.c"
    "${SDK_PATH}/../../mbedtls/repo/library/bignum.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ccm.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher_wrap.c"
    "${SDK_PATH}/../../mbedtls/repo/library/constant_time.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ctr_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdh.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdsa.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp_curves.c"
    "${SDK_PATH}/../../mbedtls/repo/library/entropy.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hkdf.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hmac_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/md.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pem.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pkcs5.c"
    "${SDK_PATH}/../../mbedtls/repo/library/platform.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha256.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha512.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509_create.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/src/sl_si91x_button.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/src/sl_si91x_led.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_si91x_button_instances.c"
    "../autogen/sl_si91x_led_instances.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/inc"
    "${SDK_PATH}/../../mbedtls/repo/library"
    "${SDK_PATH}/../../mbedtls/repo/include"
    "${SDK_PATH}/../../../src/lib/support"
    "${SDK_PATH}/../../../src/platform/silabs"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../wifi_sdk/resources/certificates"
    "${SDK_PATH}/../wifi_sdk/resources/other"
    "${SDK_PATH}/../wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=1
    SL_MBEDTLS_USE_TINYCRYPT=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A06"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SI91X_PLATFORM=1
    SI91X_SYSRTC_PRESENT=1
    __WEAK=__attribute__((weak))
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQlz5LiV5l+pUExs2DOppKRSnVtthyqlqta0VFIos7rdazkYTBKZSYtX81BK7ej/vgB4kyAJkgABeca706Ukife+7+EGHh7+dXB7d/PfF4uVendzszr4ePCv+4O7i6uz1eXPF2rx1f3Bx/uD+fz+4I+DWZZmefP9bnGxhMk+/fXJtl49Aj8wXeeH+4Pj+dH9wSvg6K5hOlv44Pvqy+H7+4O//uXe+eT57j+BHr6CSZzgo+0awIJf7MLQ+6go+/1+HpiWtg7mumsrQaAsw8gw3TnQXR9AoTC1B/zweanDf2G6RNr9ART96tWnjWsZwH/laDZ6qbvOxtwm79Bb0wLpu+XF168Xd+rdaqUu4GfzHRQe+SZ8g776qPzsWpENAuUOBG7k6/CvrRkqthaGwFd8YAEtAArU/mgi0koQeZ7rh0pgfjh+919KrFkhKFFIYAJLdUCoGmCjRVaoPmpWBAI+kBpVEYF98QG4W90sFzgxH0R1HU02QumeVAsYqs4RT4MiIqi71YV6Dh5NHahQBB88dR1N9lm7mp9CjnwthDK5mahBVye00Hct/qBSLUQ4nulwLUBl+e2FeR2FoeuovCG166OCuA6do0kxVhTSgjyeGuQxDUgLAC80beBzR0fSRIQFbMtcq6hfhb3BOtpyRdaiLAb3SYn7blI/rkWhuwUOuSOv5ojpBKHmQJhznSmRBEStBJT0URXSPAVbU3cjpOpbJzNgTVkfbJxNV1NGxGaZzgPw0RN16S7mlsEFFEFL42Bk4dqe6wAn5GWhupKmXNPTr1RdCzXLZd2yFPKMqKoJF3hEH+40x7CAzw9TTQ0dHm51rqamCY/pBqEPNDv5lmNVI2miRsXNUCRNnahMxwynaJ1aFBIxznVfT/ta+CcXWDUd3T363gzgjN5x4NT9tRoYD+rr+fH8daGDr8zj0/Ym+6L2jYFnSIX3tS/idYXSF4RvYONf+aT2ka1HtU8ImH1A+Kr+3c70iN/VsSHTEj+sfWreXn9XYb5tGxOQkxhu2KwjTlQoW35gqsFzEAI7yX08Px1UxsKdCSdunuaHz0qcT8re3JioaCh57itxJqdf4MxSYG4oyNgKsqQCjaRk7JWMlNKIVaFla3p2pGqeObDl4c6whK+ZValW9n9dav9ie2KQEhilCqfJBmUOIVQeefKQqOKhYoFKtxeoPuwXNpGjS8CDgIiaiQFnsHgaqwauLFxqmMhsWqtPtcV12trzik2A77sDB6vMbAEBKyUsVDm6hhjU8NkbOipiCr8Mhgq/AWcU0uAvg6HCf7c8foL/kwB8AQl1W6DrHprd2UNXspkX/jIgeh5QhiwMEiiDehY5KFQQUTMpjQAl4VLDRMUGpohVSMCihIUWvTSVuoSFFr0WBMAP5UCfY+lTo6WqAyU8dOP24mBfPIkqHDoOeKVZmmpchdODg/0oQ+dWwtJ7fN72qtWtpPXb9kWbSrV0IEs4rTdd3wxNkNUJcTOgZFcxmQM1wxs0GSKM9KJg5AYpQ9YNmBqoUmalDKSaoZG49akWqBflUC3whrHIWoB4FVYCEjQTrwDEegUWIGyFtMfO0LBrZ5tfVFb6fRO5GlItrtuBGahxArqCubheXi5pl9nP2wQTvr90dCsyyNsCeZJCvscK0H6rqLFyYmylaEkFG0mJwSkJKaWGlXplPU159u2FUIyB9uV3sfrxZfBLgA7gp16fLV4MxxTsEJ63P/76cngmYPvy/GJpwe5lsMyg9uV4efJCymsCtC+/68Xly+CXAO3L79vZt/OXQTBF2pfh8uyF5GACtDe/25fC73YQv+/Ls7vVy2CYQe3P8fNLYfh5IL8X0sqkSAcwfCGD0xQpHw+XPrP31mVADq65PCxdOGJEdurtZDX29BNnVuSDU70yXf75OOXUu0TlQqqp2kXrXKwE/KtUI4avrcOCEnCp5hqt84kSbKmmEK3ThBJsOOlVr86+vX93enImD/4qKgoiUk0AWgf5Zdgy1VL6Svr9/Fqi4pKioQEu1zyjYy5RgS7R9KF1ilAvKiJ2pZqLSvOuVL2oyIM8hTNu+9F37V47Pb0235Bw3XoQO3LPGWbbcEVc1N4/KBHYeqYrI5sMGL0zk6Y/mI6YrdEWMgVYvXJG98V4WXaVMr+fqyVOI8ZDrotJP185XCg3USDGRaurtqTAetHZmLaMZBJYvahsPcPWZCSTAetFx3P3cCIfaI9SlrYyun7E9lIWuQRWLyq/BZ4pI5cUVy8yvnwdZwFWLyqhtraAKvK4SwepGsAB9MQ5PFOR6+cAnaVF4WqkJJUC60UnkrRLiob0SCiRuvc1z5Mzi6r4+pGzvCBAEygpmRXBcXRnh4YzvR3wNStBQXatHO7Dq1uu/qBGnqGFQOiyQ50p9uqt4qM/1OeLOZ7cwacAjZpKPO2WlEwGrs9BPz+UNnNydNSEcE8kJvQEBaEcHTUh3BlJSifF1otM1glJTKqIkZ5cAFFJyyoFN+FpjFJ/IXLgQLALGkBU8fXqzyTkU4DWsz+TlEy/NW4telJ9sAE+cHSgPrpWKPI0WQe9VrDUuacZ0hbEBFqPABZiF4va6pTeb70IadV8LRQUiIaGUQkhPTGx+xRthPrtVeiCfQtbmfTbpDQ0aZuABBp9XyR896itL+q9gwScHYo5aQjfRmpjVcFITU5iTn2piN8aayHTf3tsK3rbpY1N360X80Ta1i2B1oOKtH1OAo2eirQDG7PfgMb1NFtMRBYKLhk4eg8fwZvHLWT6biD/BqRtxBJo9FQkbpB774WjBCiibijtokEZIf02l+AN/hZGvTf5ZR7Q+L0HNIFhumLP17fQycD1oGMDaZvpDBw9HXmXD4OeDrKBbcpbzhJs9GTk7XT69jmBzFx6k4n3NGWlk6HrSUjdAc1Ae5tSEyui7LulLCmxHF2/LWVJ6fT2vZLG76qD1CDfq3jXVlZWKThqOo+aISuZBBo1lX3ki3UvbeGSYqMLTGuJDNLcwaYEjpZOEt72VPWkbLTrCDn6LEYOBA4MdN8NY2fFjEbMTRXuF1egGt8Q0wBwQgcYIgSRRbJoo1JZrACkrWoS86JixLSOcfcPznKroEmaatfge9aGWURNrMKQodR2dRQEzP36whfDdDg9kfdkDGHZeZcGk6Zpp/nGXkN3SfdpkOLrkGmDO7c1X005FmsQ2m5VTaPEmMqNVo6zsUR23QNI3V512EpkwW6yValU5zgH2apPs28Bg2fphOLlKpoQULlcJgjFFUoEQKoSiUxUKo4JQtZlkb7thdNWxIGuyXUe7dc8i3Tc26gbFP9ZNZ1wI7SAJ6ZREOtywSbibAlhSSSLxKo72PtiMZIyrYOcvDZjCAbYaJEcrvIlY6HK3ACwb3moFyqpWLbj5N6Z4tta8S4CpwYok4+Le0xVgnOHaT7k+LIK2o5YQK9rVjBJUYALhouLMQmlwP4XXzVngUdgcQh0tnbFDoAK7LJ1/wQT/dGBQIKIEiQiRWD0TqmeHUnHJAVF78JpCa7cBBIJJnoOEmZE73yQI8AUkcqw6FKe70KsgQuTAicQfDaNyIsAkN7nEWyFuzyRSBVw9eASQn2m4EUfMpsCMno+gv2diEx6ejlBAZ6sFaeCrZdjE16slnAsU8FG7zEjRaQiEiOKMEUkP5O9IdYzg0QlBTV+A6/X/aZ4MCV0yliwRRpYIwXVa4QnG4kE05DRkXRUStB69VGyUekd+6jQD8jGpYJtUB8lHacytgF9lGyMSsj69VGyUUlBsdtdb3jR9Ljc0e1NxDkg7cBXvrSB7frPDbc2Fyxva5bl6uo62myAgIhnKSElxqvU4dQtT3tzNfB9x6W5t7p5+EDeCcCCxZkKqy9vA2WIxl3q0Lx2WTJErG3q4WSFPxpFZkB60aYtP9C6Dgh5FCAoFu3MAN9BGwOhpk/fhmfWjFlWdhWJ+CjuOomFqbgTCE3LDJ9lIUaARc8ntgqyyNbX0MKFutMcwxIQfbCFXStIOq557us+MNAajWYJ7BOaimYF3CRtHqEICWsAE7sku74EWCxKtkTsWkH25CodL27dl6nbXvf4L4HiobtzhFV0BFWpICHapAm5sEytISfmJm2WbUzfxv5okQdLukH2+ioZoZIC1w5x+VjFX32QwevMXGJCYblMx2tU1jcNIdtOAgnsmesno2jrrBxjwxg/xYCwwRcMTlPXcFisbnz4Zu/6IgfwJc9HIrDhxTLc+UAzYMNGUzjN9EhiZIVmnFKAD3RmmAy70gJtuGl2bhCqth5RTRCRcqphprl/+nD8Tg1cXXV0T0VKxFkwpZg8bwLHZfii7dbxHHSjNbg/D5uEozqP/PEgLXR2FlYTcfYtcczWHOvo6Ma4nqWFG9eXik8FVj8iaipYUkYlfH1m2OtINkolXFRUUIuaNQdysalBoyBUrXiuVNWIjK5PkYs9ISWiVEc2yTpOErdcxCHPBmMUoqm3H+WsOd5qoaaGzx6YPkBFB5UyMlo68TRCNioZKkoa9qlsFGJElPBd6QqT26cQeQ9wwLq1p3d26iBRxEVJJQrkqw0pJkoKezMAqMvKzlkGIIymj5TcQaoZJS1NS3PSY1eCDsB1USQi7EPPABvTka+nqWIbMHSViBEBWk9CYk7iUFLqOI1TCwuENclFpgCKz6ZNwyi2bRVV3OaHU1tFbbILeRXVdYJQcwTcolOlQMDThwbaCMAGMEW2kBUuVVD0hESPxAkxxfoRwOuWWdWVhEgdFD0h0w1Rh/AABA5sS2TKgOiJ4Ij6umuJnreWI2PVQNETQtcEyNaO1TD1oBNqYSQNjwwMPQGZylWv4oRViR7yJPArWKj3yIiPCQ9rj+oPuqPgVGPfgBBtd6q25mjbWhQKir0iknPJWgtMfTJnuCymR5lK0cmPCKiaP81MYEuH3klCo4iGnoMO/BBq1bUQztRDOMyRgwwRFgUrwejrKMmVmGY/u9npTgjHeM+6AqM/V9KUjMR0mlFAE9uCW2Fr109CbjjCMScQaNCa3gSdPAXkIg4a3FKA7oUY65ACdhkJTasqFnAdJc0oqNb0rAMjmWW1D2c6mygIyVhPYpMcchx7LVXcmmfwKzM+cyIIY0E7DdC38Nu3AqFm+ttrAlTJ+a7tBpi55naA/Fc0mgA2Ll2UAT5P0/JV0T13N3MR51jcDdAiUmRtFjO8tav5Rtv8LsY6cloXxzeDmriOSLGGbIbtp2HVErUcRqC5fJ5FokQrjxaXqG0trdmXye5j5PP36G+GWwfRNaLAsdYFWLimuguoeaILwlnS3AXT29uCYJY0d8EMhOV60CfTk1vpBCGtKGffNaTL8229A0I7fskPc574bEfKDr9MF2ZagPBarEEqpySars6kevkszDQZkmctKRMtLqmTgXRV7zjpJKtLLdD7LCrhFBNuwjbD7t50JWLnv+jRDJl6mQPXHCEY+bTzsX9a6xyg1oZXbTLFycIYZ9pUN5wf7F7cqTdftRsVDcNEI9Q4CAfvfdmEVnphIkm30gpXtwMzmMQrqQy1prcD5iQtaQVic+tZG8EDAN4fnUzQBJUh1vR2wJxiFb6CsHHBvakVmA5bQ+nragOrP8sthJ/CLLQT1TYz33UMKi1nwSTaHoVjMyHu4jbl3AP2XOdxZWsGXCniU7phKBQMPN98RJusD+AZJ0X/CmDQAKOVAWwD/I0JLAOOBHGiKXGTlDej/T3ygbrWrNC0kSfh1Hgb1Tci1jUkYVKUZZXNyHCBmR5dTW0HwrQkTwuwoLURH1qMBv7kFqyr7UA4tQVrWhvxIUn48M6U8KpKm62H5RX7hmnN2KieEvHk+d6kvRGv/WyAxwczrPa7UyFu0d+JeWrrEvR2lQNjiyRM3Us2KVeop9xuuKu4SpbYmY4Bnua70OZwm0zOCYNQyroaKZR+ln+UqW2B/uAiTerp/HR+kpGsLi4nsRxahtidyxIUM/nQtU12R80ybkoKvzp7z/S1T5TWJrvRfyeoRBnNIoIbnLA+pd8Jj6S5FatZSAKeQjXUggd0U4sZhAxPz3Th7kTRbm/gROwarE4bp9raMWlBABhOS7trS6ava+Vo4hJJVw7hzM5nGQSxE1eurwOXBQvhhLBSdV3WYrqUSmEt0vJp9/pw52J3e81ntQLezC8NttOBgqquT4W2oI+qTk2GK9dHU6emg5Wq67OqWSvKi+vl5bJtBLVw/WqMt8oXl45uRYSIqOV1DFwS0SKtyTKEMcFKmJGCYCsJMqWuvHUDL/4cXTzB0hGqD9SC7lak4e9o/yKElXtimGXFFNbc6lzH2I2WTPS2I8TrmAyjA1ECLKhtxWd7kar59uO7iQGW9DLwmb9b3SxPmLUlsFfjbw8MuVKkEsWtWeaiC251ds4slAALavs77SwxonbTQwXoLh6T4bUYHdRiVEpZMXsPB4pjrPGpW9V0zI4zHzT+bAVhqgP/5GnO1GG8oDMdRJBg8HH3qmniWDVIhEtBYsowGDRtpgtHiUCzxxeMVNIUBSLVlZaGou5Od+bkW9UPuQ56u7Cm+vmU2swiE5TWjGHqVFHQ3Ss3BGJN9TOoUvGdb+MrVCwH1/gpymmsLpuklZVTuIujzx+A7wB2l4j2RZur51OpikaZoKwmHHOn+KLyfjkiCm2unkXFsgDwcMA3BpUrkzVJac205YsgRf0dmWkWPkcxmyfJzipkEghO1Sy3zbREs0Xfov4eeSMEbhUA+ykGsA3/sW2CQdjO7J/xQHcNdi79BAtiGsWF9Ewjg7bJebRfjz1QD0WguKNaZHHtXmI7IG3x+e+K2vbD6vDjibFRYVK3wAE+38kZyW4Ftd0YObfcJHzEdroBm7qxtGAnAGGuuBun5fJdnCJBTHUOOCbXNRIpVr40mLJlOg98hyUFkqhvbwdBmScTw0119s8Ty1y35wn8AKtYXJ/iVXhtEmZQq0LQzKM3r1qg3yYxHNXrLsMIaUSzIGugvC4oY3oSKpXLtSVBJPA4I1fWshGbfDVNT1aB1tSPjTtrgg6wNPvAFaC2lcaND4Afuh1ROvAGB6Fa0+wTNG7SsC/hyCKlL1J28Q5NumdQglBrfxviZNLtR1XIpvo5bUp18U23f6owCNFBiahtz3V5jKl6486AUOUWTTcVr5x0FWnP9UNtbZHzufTl18WC5sa7s7tr1P18obn3CCmftJLENlFS0grkpKSAlRQNxUUA6FNb03124Y6YoM8gcbkG4BrY1xrNpZs7oHnqqdCMTbAqOZRx8YJJwwOa5pGbj3WnKRKASpPXdQ0qLDoRCuQmEmwRQwdcA3g+QEcOjPiqFXwwnIcHJTX4ZkQdVMAjOjGzhdw9oQSqODpgf4FikKeCSMhFDB1wOfn9UkMlOwLXYEI0gbYF6jrabLgsCFMDriPpgu5F8bUFbA/hD4FeQ0IBfe9rngd84cCLODpgp/2dSMhFDF1wffefsGkUauEihg64v0UgEmraDEAH0ADY3k5oW5Ej6IIaolBTeKAqtBhUcXTAXqLPr4WjrsDotDV2TBHfk9SAdABHxzVE4k31d8FEO6ZCy0OOgHqRhzTiFzBTK+pu3SAoDUoFAK3qbwXL6RxMJ0jSgZiG7kwAukxxuydEqZEQALMGoP0ACmwjhBTITHE7vLhlEIEv08zCYwtsu+9Nwp5ijybYd67fX3z9enHXtWYTf6XerVZTmC9mqOQklFi/UobRNT7BH0/RFXXgpRlL5cTE401hDF1277XBVQkNUVwn9Ly57nlDzAEnNI8mOjOn4D04LXR9JROn1FXZmumw1JXLIyhDEXXfsdRWEEhQdwbTo6PNMM1PQyOwgSfN9iz4LveciwtZDqeuphPL9RoYQ+3QG1GujIDrNk202GnOYNdeCkwkRRR4cIPHzVCN2tqQXTjI0W/gFKoPqIIiGjwTmKmkqg3TdXzfEH8bFRTR4JnARiVVbZhuk9jF/I1U1ESD6OfjKQxV1UaF7GRSZCfdyJawH4L5zT8TC4oo8Hwd4/YzANbXqsdPu7UmyMSSKgpMiygIXXtCZEWFFPjOE5/q6QCWNBIQfoZy3w6MFoC88bBXXuShLQMll9WsaCDzBlWNrJ7h4Gnl/ohCvTFRV5LXrpAVw4pEgtLFj5e3V+52OzgqU1WnFQtTKoIJqlfgKbxxrOf0K0akUwBE8QQYS1z8F/iepeEmqNamqtQuxSPIt6puYs3A6FW9XYZG9e31+3joONzQAQgjD87iny1XM5SqzC61I+i2KG6rXLeJla6B7foDJ5/VIk6WS5poPwfoIhcUUTtaB8y7DJJ4AgqNxS3eNpy9hlYA33kuMoav+c+KVryRu6wzcI5hwoDB0jZZc1F+g/69b4Y89WfyCfrXSefGRXkunKTZ3KLQiZw0Z8IJmnWdl9pEMkmn6e1YbEyQ1WbCGzVjvxCu6jMNJAzJZSEqWt7nhaKqg4Qj9FXDXzMIgkeGUBBP0A50Y8dJcyqarDXQ+KmNZRP18ipviWSyTlWP/EduHUlZAQmBE/qux+C2JrL6XDpB9+7B2HBSnIomabU1nWelKskn7UgwuPmWqNg2GjTi2124qEwkk3Q+6MEbXlpT2SS9yVCOl+qCeNK4dKedvHnLSXcunKz5zTGDM1hNmhPhBM1Pb44+cNKbim7Qquo+0LiNRCsaiK03u3Bu8RdqOhNKEqTAQtN51v1nL47nluglI1JZ9NnDQKktfTp8yaJXHwqsudf3fZed/00vXKlmAirXZHc9eh9MiV5iey4EkPfQiIfRDGEQqLa5g/fAaH4+CFnb3N17YDRzH4SsbVafdqv4Ej8x+KoImvscdj6PfQAWlTdgwxZW9UBMe1ZD0LBwuEAp3NuzqxVMjn+wXST+5enD8TulTRMB2N3F2fn1xdw2WHnuFAQm6nS8cB352G0l1ZtsQUGtED2wSk/wfe4L1/ZgijW+2xKtQvnG6evX77WPR3P0/86OTl6hR0dHJ/mjtzAxysZqWluP5hocu+439jww91toJ/v4+NjehmsUtCN0XUvfaaZTTQffBcZD9anuIinI6HP4do6PGMxhSQH+R3zdz1w9ffP27buT0zf5xT+2awDrowEC3Tc9ZIe/fFLqz2LnsZK94LNP+DAL0EP498HsYHl5fXt1ubhc/aouV9/PL2/U65vz71cXy4OPB3//F7q503YfATT/x41mBWAGTReZFiyyF0/YmzyAb/7+j/xxHEsAP8XrP1B3dt4u3+6YZe/uVhfqeRxkFvlold7lznYqSlp+iaNJxGEkDLCOtqpOkO6ZDvE5usMHFQu1ZJ3mb+D026q9dUCYxa951KwoPjNW+gTfDa+uozB0HXUdOkdNaKofHlN92EIv/s4CRuMHeVi9/AuUkbAgReho/8f7g09JUfl4fY0fvnqyLSf4mDz94f7+/mAXht5HRdnv92kphgVaCQK0S4w+mgOURejLV0kJwclCP4ofmgb+HenzWO8c76PMIz0pLFlTMN/qOk7hGXZJxF/ucUHHpxtQ6xHASovalVjR/D/RfxX0UVbyUzp/wSZJYEHCSOIfs7GFXotCF6LGJXuR3bKb2D99GQc6Qo2junQXc8sovY1vzIlTqroWapa7rQhAVxDhQwY7zTGseBW47XUtdRaCNv4iqAuofdEsA8eHNvFCrE76sFRq8+9qKhu+a5CHSnensPJHcpXxFbBRxwteYCmve7POmr1XZ6Rt1urDXfYo9bqYFX1HZnUPiFnVC2PWPjSa1fwZZk2bsLPKFviM7AJLeJz5hs6afC9JLyqySs6BpBeV74uee6Tnqe8c8d1J/V3JKYr0Ykd8XHRVIrwuOQoR3hecw2alseSM5A1RfRinIrp1zLJN5lnBa35W2QaeVbZlZ8Vt0llx53KWbSbOilt8s9qu24ywBzYr70fNsgWwWXHhaVZa7Znlu0izwtbOLNtumVU3QWalPYlZYYVmVrtRsudlQIMEJBfLDEpbuN6nb3o3vzOmZ9LSbS4905av++lO3HJtSt/EhStNaJMm4b/KV4a0JW66c7BHmiy+DH2a5NJN+gSkazB7pB6QJr0Ukj5FdtNfjyTZLXx90vh5j0eXpvM2TgpJtZvq6NNk17X1SJJdPEedpvPKvzZJzZGdu1PVYg33TFIMndw36bbUzfZKmgT2HZAsj7bbN3EaB5cyXUNEU8rU3YFp+wpKQ8a2pyME7eyVgD5TCTFO2xL0vBuor6iWe5VoRLXdATMmfXovSy8ZhFuBxqRPb+qhkdF1m8AgGdUQ/z2FEK+cGCSDdAcElaC2m0wGC8gvF+khgny/zWAB+ZUzBBHDw4iyENY8bh0ShraXGEKUkCHpq8E7hsgghZobI6cSw2eMqNax96Cgi2PkNMc/HCO1GpRwjKyWEfqIqHijpNUC1Y2VVoweN0ZWMazbKDmFeGtj5GSx0MYIycOUjZJSiR02TlYlNNYYYWncqlEyspBSQ6S0TPVGRmVmKzGLlDxKbD3K8BBxWXikIYlrQYuGCMlCCg1KnMX7oUlNET6GgZg0ag4rUTGq1IV6VnGZnhWDqsxSf+ZZ5rQ2yxyOZ6nb2KzkrzUreAfPSv5Ss5KP0qzszTsjuAnNii63s6IX7KwUjWVGPjIGH+/NAOiu4wA9fI3t9np+PH+tZLuYgYL30lP3EjSi9gMz3mBPDDVGBHEff4BAOMLeeqY7FheaxZ3oDKR4e5uBlIAJI5jzfjiKFJrD5LmuU4qorBwbBh4iapWF0L5y4lkGqgBm+DxURrK1MxSDCQB4f3SiFodxvWV4o5IPNEAyG01T02ZlvMyTFQe0P6/YeoS3aRR9Z3oY1t3y+An+jxoTnVS0ldfTVHSCDS3UuAiG8/zS3gpDuaXNDYZy4w8Zy0VNho42N3mAxsLhDw5i4x1X9nK9oOzTxVi2D0eGm8jROUhPVq+4oI+9fbgUwFi0/ci6kCTmwK8ZikaNs3l7/R2tEWzjvww3hM88O1I1zwwYttdNumq5jb072epFOgwAPLw4rAauzkF+sT6wlQ5HDj6KGBHnPmPZxYLFRnQ+aojNvo5YVeB8RJFLZoQZ+7qm3UcUlFxdmcpHe1awCpgunHSZgHH7nLjsJgZqUDXWYoZvIjebZPU9/pV4iZzHP9KV/vinujj7Nppff6VshgC99V6sfhSiVL0+W4hRfPvjr9Mr/lLwEZhQ7eWJACNfLy6nV/rt7Nv59FqXZwKoLm8FKP2+PLtbiVD7WYhSAWUJauXUFE/QxVxwa86/civu3BpHbg0g7LrUq7Nv79+dnpzx0cCtQeOWi9/Pr8/4jBGxZD6YcWPKBzS/dppbW1w4MFk7VsZPVe1s5nhVO8039ho6t5k8iM975bsV+Rkw7jpTt6qiTlYlrqbTAkaZJHzAjyHSVqKHtLHi5gEfn3TRrEwfYqZFT6oPNsAHDiw0jy52oGUyFe5QrCM3WzXyDHSajrMuNAvXjPHroxRqdN2cRA06kx6fP5xCmz+N7cbvm1BpYdcGt6gxtElsBjZRMEn9AWibfRJFzg6d/DXUjWlPoW8iNVvPsLVJFAXeJE2QeTJJATdPJqmu5iQNqetp9vg9KQpF3n6SQv0bmKSo/TZRkUZ6Yj/dKbT5DvdBFlYzVcMTGKbLbi24VZENJinewTQ9XmCb09htmloUTKUHu7dNp0ndAc3Inaa5aiy5Z3PVFE3UOiA96amFSfQFGgM/LApFjxq7JYEWNfvIH+9y0qGnGhuAp6LERedU9bgWc7SeUlpq4Liekm74o+nyBGriGdkEipKGdgJNpUMGXDXhZm8iPVmzN4U+3OyxUuS7drrCnM0sNP3BZDhyJahAj3TrgV270KSD4bJWkwp2TWmDBrYLQE1KmC7+NChhuRDToILtIkyDEs/do9Cx2iP3bGE5y29QwXTq3aCD5US4QQU+yKeyOqdApYyNk3CXqkKoB25KmE4RWnQwnx406bK8IEA9DDNFaegHYsQf1htqNWXZaDr2zI0D96imE2746CztUdZ1shp8NOushChirbA1rkohnAkXjbUgLJhozJvxQDx2OrfAY3wuPDnpx242S5JvBIzbLJISdG6CqwLPYlgGSPJ542c/RCGq8V0dBIELVQEnYLhXTVLmgy3TFU6yjhCm7XNgeZAWhquaJPnwgTdFjqCKrqK5Kuc2hUN/TtCy3xvsJnNFBenUHbdaPNr27GiUZfGVn7cqPNXw6gKzRahC9eCqp1A9eOrJqwdPLbh6sFIQOebGBAY6+5iOcONXKtOFCIKaeKDFW1lpNFtUxtqAXevvXBjSKGV1Nryv7sL7qbiXMruqf0yG7010EU8QKNpujaZewN9o8JuCj+BYC3doYBRIoUsLtiNPDVm4cS7SXa7W8R5C1d7a44YmHTrQQVye8pFQWJnUzCM6vm6Dp0ZLc9KlCwbLMzTacLBEfjUli8nLTwFyiNmjS8bw0f0J1IxfKWhQlA5a0NIKKnj2KQoawKMxJmlyuWlCAajKkcN4qlDTzzjqinvNdcRfRzHiMQct5crDRA3wfceNA/mgv9hUlFhoyTKxdCaQN6Zv4xY+8ra+hqIQlx/E0eAmVMXEZjs3CFHtTp4XMlp1dE9Fr9lwMnXbSy+y8/KrE1hLZWKUpFPC44eeMcto5Ka7D30DuvWRjcoKhm6y6rcJs0wOgnF5zBogDgpMN0Sl+wEwGnaWp2jJNVcsZxYlBcjLm2fB6RnmkF4we4Ps4ayV6bjRxheyKbZmWbD1i+PVMuq74xYqRY4aK+ZtS13F+F38LuG4om7jOKiVyx/ZKEz68qrBWOZJQUUzJw4Kk+1gqFb3gYG2ZjSLbWmrKcLNahLMNLsnZqwuv9ZVspSbdGewSq5RRPMNnOqAveuzBV/q0pgIDnc+0Aw4HklGz0i+HVmhGb/ocTY67VEU1NwVmz7qetYogWRWBkJ7907NsgYOBpoF9uuFynKSAXJi/WH5lxS4JuvTCk19L9aBkYxlYs8dEBpranbNQkz4f2+h3d8ykgVFjZUUwHrVwyG1SUq/cV+TlGf6ItQgIuqxfJ/5EoEQFRLVjm9lLXTGDEUNqL4UQg2HqbjeYagpZDIXOKC9aZKatTz5qK5vS1ETmY16GIpS11pg6qoO/BCSR/fswJFGfu0bSxUDhkzUwmGTje5K75DsgyC+olop8A0UbY/2q02A7lLPn8/x7Qpdh5O6RXpwjILM+gCescgH0DF7aBGJYsJuTGAZsCfCwgYJ+j3yAbQbHNrY+Prb4aJ0Df0cnhxbiIGI1LZDJNjPcFj4YIbVrB8jawweVOaBP8oosYhRIPAQuVgrGIliAMrYoqdjii1q5/EmYw8BbrjDnYWBbpIP7dQh8+nN0Yek0UF/olYuP/aXPAkLP/GtK6oe4EnLP+BD2zUiC9wffLw/+IRutYIAPl5f44evnmzLCT4mT3+4v78/2IWh91FR9vv9PLbGHLaWCpy93MYfzQFaRkRfvlpHJqzhDk4W+lH80DTw70ifx3rn8dZn1uQu8U98VyiO9rPVdZzOM+ySoL/c3zuvXn0yUexFdPV28MrTQjRTxV/N/xP9V0EffVIqpP6CTZGAg7SRxD9m/7o/8IHtPgIDPtrALgLkH1084QCPAXzz93/kj+PbALOnUthxgbd4Exm3cCb0GSY2/teeQ+2ZHGmApRKm2Ab/a8ihhnzxRfL+QItCF6JW4JhMz4Ka+zK1opGepp/cuv84mB0sL69vry4Xl6tf1eXq+/nljXp7fr08+Hjw6a/QBPf3r5B7GFT1w/3B8fzo/gA+AY7uoiUv+Oj76svh+/uDv0KdUGmiE37iaDb4gcR1EWdBmSoSCtN6sLd9XurwX5g0lXWARcMP4P//tHEtA/i5/DhDS9+kX8Jxff5dfn2aigCgXhi+TEAAmC+xhdFDfCU3eoILW2zOVtnpzDc5R/WoWVE8E2SmIb3tdZH5ALEEH69ZWsAo+Bgxk1+P9ckSesMlbVxUhL5rMRXumQ4Pi1fCjqoTqVmHztFEeo556clPs3FQAGzLXMfb9fgykpE6PilxW1h8ZMYxzW+1cAd/Rr6JeIWRYbof0+5ASVvMWFbWTeBfr/g0+StgI2cswKrRT7r07la/WnZMvOCpx+s98LOsl85NXs+H3iU017LjoQU11JyJlFWwZIFLtI+eqUt3MbcMhrLrEaxZWiab66q6FmqWu2WtIL5bvLC1zk8440JjusnFv7F85qavyeeFH10TP77gD22Zs2Ztsqa5df1mcPNMXhMjtta10XxaewlfN6SJN+cbv29IFc/fOlI1poVtJFXSBgG2HvVI3mgrv4s1vayd6Q2U1WQjNMMeIbBBbHYlIAPhbSrQXYPMVKSKSs1O40WG92nzgL7/qPzsWpENAuUuW1HemqFi40m/glxQtACUbxCPvVTwniSsfDSnw0Zcu1hvXhnaqHSxpJR2KSFkZQtC/yFaUKXLrFwDKTxrqoDG50SVcfVSTfGUq4iYcyZcUyqcNQETF96161+lYF5DNYY7g8ah3nc6bHr9Wn5kV14LzYfs7ocUDfOyV75MXjjZMhzmbMsHs4WzLcNhzrYQ1k841QIWLu0nuhc5P9gvnG4dEh/WUJ88fBMw3McFshCuYOLCuzQHkoZ5DRVz7lB6fvxKOOcSGh5cJWq6Smh4cM1D6cvANUfDq92SrO6WELGftxYnxjJQrgJizzg+4CVPY1UFxImx/SjH0KOERtj8dFxiaiejETJZLZDXmjjnEZ9rMF0fBwTIXN4Elo341t90FaMZoPDlDOI8Bnl8y9BrxFZsQDXKdNSFSA76zeCGWYF1Y4FGay+kscCOSGLbBmStwgpngkd4UzDVymbMWGjFwjmQhTFM8by0vntospo/QRwPk9nWuh2YQRJwgG2jsLheXi55bLKfjwfbKv8y9oXhu78ek1AXImfyaWjVYhlQcLYpMTwlMYVSQ8t1Xz3VdvbtxRgmhjqFVS5WP74UqyRQJ7KKen22eEGWSeFOZZ3bH399SdZJ4E5hnS/4+psXYpsM7BSWuTx5MTUqgTqFVa4Xly/FKgnUKazy7ezb+UsxS4p1Crssz15MaUmgTmKV25djldvJrPJ9eXa3eil2ycBOY5nPL8cunye0yotpc1OsE9nlxUySUqz/jt7ZPFY6GWx2EYsO8XSeFKUn2VqoA2TvAkg6DC+bDcoAhS/Ev4xVPaYLeBXSF5ItvFwwWFmpUPwq2Xj1K4NBaYWiZHN9BvP5CkHJpu0MpuYVgrc//qpenX17/+705EwmplVcDClLNrlmMIGuEpSr3WHf7Hw/v5aqsKZ4WFKUbVbPZOZeIynVBJ3BJJxUUMV4ojQX1LGeKKSCKhPHFJAMjlO+a3Pxk+DmuoMA69aD6Llsbrf8avYCMi5+9EgBSG+mlY97Bo3PIQJNf0juH5OLegEYt1zXfVEnvrrKu8/v2BeWL+qMTBdvfqdlcFXaRIGogxRdtTyFxo38xrTlpJ4A40Z86xm2Jif1DBo38p67B74aaI+SlvsyPn5m2Eta+BNg3Ij/FnimnMxTZNyo+zIOawrAuBEPtbUFVLEhGjpMUIPI2RgiD41SmYLfIdJMT3qzu4QmSKFxIx9JOwSIeI8AkAJ172ueJ2v2VxHyM4XlBegWngdJ7VCE99KOLKWGryxYwSw1vR3wNSthPPQwUoN8LqcJdcvVH9TIM5JrjAQWlbr98PnCKkI+IYB8UeHiOtgXwHEhHi+5SUs9g8crLJAfSpzxOT4u9PFYRFSQVgr6OT4u9PFwRFryKTpu1LNhiNQmKKLkY4pAi2/sk9QGKTzhDn1TbM+V+nqxA1dCnqABbBUht9GIlOwL4DiORqSlzm9/UoueVB9sgA8cHaiPrhWKjd3SYYxWuFxKhmZIXCUScJxCsope1G5rC3R+69oIoRZfayIv/xJGPmYQvX/dRp/fHrYu/KxJK29+LjqGJnFDl4Dj0/dL4LHQ1vdz9VoAzg7dXWVI4LrQZoMKSi6mkNoCPInL4LzRQp2vA8dW/OZ9G3eeG/jmicQtfgKOE3GJ+/gEHB/iEg9pTX5DWdfTbFHRjimYZ/D4eB8Ld8tqoc7TNes3IHHDnoDjQ1zqLo2rTxoSju7cCyVezCtj5OOIIdwtr4U/V9c8uYeyPtehbGCYrui4eS3kM3icyNtA4o4ug8eHvMybFwHHo1WBbcpc4hN0fKjL3Mnz7OMDuZlzpR775chLPsPHkb66A5qB/HMkN0MRJ083KmnNkOPj50YlLXmuPucS+Zt3mIC7z3nspySvDVJ4XMg/aoa81BNwXIjvI1/0UaMW5ik69le3WWKvX+zgXoLHg3xyWdyp6kna7dUx/pucMYkcaCRgqJpnvoDDJVk2xHmjSnDWoGBA7GPbBPF/hLstkbzYCl3Mn1JNrkDk0axJbQWG/CVsz17k2bmsbBbQS9TENZwqaEP9P6vVqxpAjjrfNaQhoOY3xntBdpnGGGLvmB9iE0b30EvUaew039hrPuDTVayjMBx5EWyDZDadUHsZjdEL7oGqGaTEqMrdT46UQY1ldrkDnx6IKs/ENilNeVZqT3KkUuQZjyGHBYyXWvchdNkqPoRUrvUJRimKT0NWTVHlkRkkq+8oq0qVPcEoRVZJNPoIgI8sy3bQ4Tzar19qsxOPL9UNuoFTNZ1wI7gRSjJIQTYtNz5EpMwumGowD4Kh7uAIHauV1jZ1mFJU/IZyzbGNxoYwwEaLZDmEXco01EQ3QORdkuvVRzK7tCOVojzzGLIGFgAe9vJ4gV1Ihh03PnH2SRGXKS1dOcKswWzHLEU5a8hMrmNbs2IZSZqHQgbGjQQJpxSZJtMo9zkIgW2BR2C9kGs91q7oKVXBZpkPSoKKT6iAQIpItyTaRWh8jlB6diQh7xQWnyOElvAmlUA5QcWHsZSZzDWPZbnEgEic/w0Gnu9CXoEL1QAnEB77h2gFAkQ+p+jAVoLjJSQTFJBxYh5CbKbwTREy9wI2PuyFny0h8uZ4ogQq8+St8BV03A6R4O18KUexFXR8ThBIErGexJ9ZuPpG9vu9IdqbnEQ8hSWbYxgXf75sAC944amQD2kY4BQWt3mFfJQTVLxH2RISL4HjNsKQjzjXWPeFPlw+5hV03EcYElqgjI7zCEM+/iVs/EYY8hFPYb1U39SynQt3YQu0c+HSpf6G7W2P/gmqo7m9iQwQ9HfkrUmyge36zwOHhpXMtDXLcnV1HW02QMg1KalZlJiVUgfEPW8bzAx833EHW5nxWL7JXQGDFJltGEDZyybDNKy5Y7vHN3YrrmL4mNv0c9iKvdHUNYMyqZlZ1S5YWhwQyl69IETkWgN8B/lAhJouYliV5X1ss4pLGxHhqIFGzRZIBx6/haZlhs/ymIAAjD3z2M7IxltfQ2vi6k5zDEvIpVItdmiFydYqecnTfWCgjQLNEjp2aKoYFXj/hv0RoRII7JySfEjcFAnApqydUtmhFSYnq0hogRc7XDF122Mz40rM4ZnOVmSTiQgpFSwDc6aZn8ACWOM3oOSxKjwb07fxMaTIg7XfGHqspmLoilTcqogsUVWW1QcZQCbFjChcYHmjYy+wEA6fIrUH1BE67qsHN2LZjsky54lZMpnoNB570SxrDSeP6saHb/auL3aiWzrQRoQmqhqFOx9oBuxQWFUmM43iFlmhGUsXcsQ5M37GUGkBJ8r8OzcIVVuPmC0cIXpMJ2Tm/unD8Ts1cHXV0T0VARaZm6nBkudN8F7koFzbreO1r402+Kwy76VE1GqjA1QwC1CgRtiEiSwNJYtl25N1fGxnpJ6lhRvXl4x5BRgfymoKQFruJYQ81gnXkXzkS8iYkkY9ZtbEysa7Bo4h9WpD4kpW3cn4eBT4+FCYVOTr2P4N18KTy6rFRK5rMH7hEm0W8ekI5yO1UFPDZw+IiFLdQbqMjTXxeLovH+kMF2PC9ql8ZGNMjIm6EhZll0cR9h7g1GxrizgT0UG3iIwx6SiQsdamqBiT3ZsBQAOOLBBZAMJIxPWwHfSbcbI2iKU5aeQaYXGHuoxBxMjDEAbYmI6MPXcVHccpklTcCeA4URcV1IKSPJPAFoTbBzAi2WgXYL3IddDh86j2PS+R2/dObc9reO407Xm5ThBqEIoERAmIWJNFW9HYlKbYHqfCuAqLLW3xs0TCBS/saeJdnqxZk4ZuHRZb2qYbom76AQidQpUolyGxpYsvctddS/x6T/myjhostrTRHfbytdU1VIxJh1oYScQ2g8OWplwlmXkBxnDED3oTkhU0Mh2apPq046Ou18OCnNfDmIMQOSGptuZoW8pwtCO9DMgutmstMPUJj2BkoYjLBigeQiFCoi9nbTxhL4PeSkOyiIcNQx34IUSkayGA7S0cGMtClQhsJGfh3Gg59GnExnqXtR3mEGSv2GusAoS33fotaJCtNtWIsclyhaMvA4eJZF6GIwGjBMRYLqY3yQCQglARyVhWklBixgfrl4RUGcvYPkg0HVoOLEbHDU3tOjCS9YphA9lRTTU0gbGeKBdyovH1IqnqwWUISjDj0/fCGBT0j6XxFsp5K5RIhmB4rYZw9KlqdYVErns4/ClWMpvgD1iyrMJ/nqp/qGJ/HtcZRNyv/20AHtFf5itifWTtan7XPZGEKQ+ygoBFkfgiCoiY80wJ68jW2fz0BoxEsdQzoxwp3+JeMlF+SUiieHA9zaQkXjmRP8Wp32YydRhjxqP4GmshuVNTPoaGeaILY1HSPYaEt7eFkSjpHkMiEFieAlbFKb5xTByPinpZu+p0C7Zvb43sIGYDA+fA5KfOUzvhl+licAsU+ReIEfhpjZauCKeapR7ytGQv39akbLTiBiwZyphGMhY70Xp3CzFWy9xY2qQuTc2kxrgwNTCbYim1mRCTxVNc9wUxkLkfjk8N9J4zU/al9XyYJjpNzCrtLqlj0AxbkKZt7uvG0AzDRDOxOBAqf++pxCxJ0SRqpyqnNSK6HZjBRF7YZRI1zQMJTNQXVcD37X8Is1cAwPujk0ma6DL4muaBBKbZUa1g77l52tyOTYmaupQP7SOaX1TbPD8l19jy1Xua3Cena7W1Ym5tj+7gMKFFio49cw/Yc93nsv2Q0VOKqJVuIB350sjL881H5Kz0AJ6xOPSvEF4NQHrzgu2avzGBZcDZAxY0LRuS+n4cfo98oK41KzRtdOJjehaNAHrx0DUkdWLsZaX98OJiKAJzTfEA3GmtmRp2QW8v1GibD/gCrF1XPAD39Nau6e2FGknHx/anBV1V28/SWEex15va5I0ARvAQUHKa9PdiYT8b4PHBDKujj+l4tCAYxGT6nCBoHlKSjC2SOv24oEl9E4e+C0JuuOs8IlKxiOkY4Gm+C22Lrx0wNKWsrTdtwgvSo6pZtkB/cBEe9XR+Oj8hGKi+xZXEK+wxRRq0GDdi/Sl0bbMc0CIII8N0PyrI8imB6rpRlmrY1Hlthn1VJknGLE65wQkp1hqFclL6QUjMgijwFKqhFjyoPtiaQVg58d2NqlPWMFsBJ7L72idNM0yjFgTA710g8lRD1/sGlYRx+Q9npX71kgkKrXmqgVotWCh6K00TDWVaW86mYkq3DD1snX7wpkV7XdMpOaYBTTtkjapF/bAUUo0qzz215qnGlOe+StNEfFZOG4rc4np5uezbny9cny42eC3lpaNbUa/bWqqrGLhsogVos3ohFdHGmJ+CACuJbqUuYvC2bSwK3Z1bdZrsB6YgYTCW8He0WxPCKjsISDn5SItsdYoxW6M1ktTDMeDVyEpsT2oIhcSDEdhepGq+/fhuEIRSasFnme5WN0vSXGK6ug77IVorYrCVwpQkH5yVbqCGpv4wDEIhMW+XriWegg43NoSKrlk3K9exdlKN9Srl5LL6kgwMTxHH91BNxxx4om+sZ2cBgOrAP7uzKD0eU0iZDjRIwmR3OKxh7qyOJAOUQhOWhQluZk0XjjmB1rwSw7V4pdrpi1WaIi1TRQmjjjokclQ/pBhAd6FJpcheujPrUZfqjHHqLlKQwMz+o9GkUgRXLtQxAUFVK9aN2xr68hwnyiaGZREjj34gUQ/Ad4A1Ek8uRPbqVTQgdZlOOOeHVooi2OXBODy5ENFVzALAwwGOBVWzTH+PUp2lyZdgilJGZLJZEIVuyOmRzVVQJFHSV7jcjkOIZwu8RSmMcmMEoKoYWSc5wDb8x75THKqNPR7FBeiuAbpzBZMqLsZn6QS3fM6j/VpEmBeoFt0moEUWRacWWw+liaODVBIPD3QCBQ3SPlqrugUO8GkmgiTuhcTjUFC17SQEPVryVu3qxtKC3WAMefJxSCyXZomMBCJNyf1Y6JgRRrHCpNeYWKbzQDPcKJBGPXq7KAa5MAhQmpJ3LljmenguwMQY7OL6FO8RaD2YwrQKIb28fXi3pVhtH8N5hF6NjNpgTmRFVGYKSSQ6r5aiomiHEBE8isiTDNjqTVL36Ysqiul7Iv4nZtDhHXpPsIJDXN9yuvEB8EN3YEQjvK3TqxEZu1NCzPt8d6mp3iB7lvwGU97xzlS6c1IS1KP97x05fPz+HNEQKavWjbouW6QbZlVhveOpN2CzPddtHqn1RpeJ45JfYzrYeEVoTPXwXD/U1taQclGR9HWxYHWD/NndNeq2v7C82xYRHVB5YwsrqZkUyFJJ4SmpTIZXfCGRtqb77oDi24k1E/wiL+m6Bva15mzZXNS1A5qnnjIoEAkqJRco060QDaY02XQGHf7anUZMYCj9PLhbAMHiHaFQqOMhFSWNBGUAzwfosIQRXwiJgxw0+6JSQ2yWOxIweERngrbQAh4DmFVpI8F9gWqQL8p4YEVJI0G1ejRTA+rj4twCxgZBoG2Buo42m5YlcGpYdXljAXpRfOVVPdDCMIA1eQwA7n3N84DPCF5R2khwac8zHlhR0lhQvvtP2AgxsFZR0khQv0UgYmCmTMxIOAGwvR2D+pjLGQsoREHU8KCQQcZVpY0Et0TirhlhqwgbbTfs7sKqfa2JGwkPHeEYjyqVMhYM2j9lkIO5HK6LJuTR5OBZQlHC4MX+0gBqMJSqlMFwWk+7dMKgO/bSoj5ujQfrz5IP9zAoVdfBQGpihh8FgTV1RMHIkg8HENfN4Qiy9KL9msB2+H2E2Efr0QT7UavVF1+/XtyNnZfHUtS71Yo+U2LuSk5DiaUoZWFje3UsjL476EDFYpyR02OFKhUmbrmY4fYRMRhBeRXI8+a65w2LtACH+48mOg2n4L0xLXR9JROoNCu1NdNhqzWX2KIWxW5+x1ZvQWSL4jMoBx1Hhml/Gh6LDTxptmfBd7n/WxzdIgdWV0SN6noNjOG26Y0tV9eC8DZNvNhpTtUFly06kqoeyHADy9F4jfpoMF44yAHPn8J6BVV9kE1iupIyGnTX8Y11U9itoKoPsknsVlJGg+42iV09heGKuvpg+/l4GuNV9fXCeDIxxhN6jEvY+8FSMUUWF1T1QPaV4OjDF+BXsn9QlwUnyeKSsh7oFlEQuvakGIsqeyA9T3ykp4Ra0tmC9TOU//Z0aFFEXnzYmy/y0KK/kkvrVjnYGg1KO5k+w0Heyv0RBVVjpLgkkU41O9YVmS3qFz9e3l652201JtMI7VYsTqmIbgGxAk/hjWM9p18zM0QKhaigBdASV6EFvilujFmqdbIqlxbCKIO0guiyBJMsqSKgzQZUe1+/jwfAY7IhAGHkqZ72bLmaoVSl0gIYZYIWCDRV9Dax4DWwXX/wVLxaPciS25YingN0ERKKLR6tAw6dFklBCx4NlJeAe0Aorq3ZcFYfWgF857nIQL7mPyuJ7DbtgXMMBQSAH4aihg4ke98M+SLJNLQgWScdLicYufg2DOYWhWPkhiET34JB1/kBSGS3aTe9XWWjiCmATHwnBuyFwhlIpqMNTXLNjIo2fvjhqWppQxT6quGvt/zAFBS04AC6seOGIRXerj/QeAKIpbci4FdCE9nt2lU98h85dmVlFW1YnNB3PSY3k5GB5PJbUOwejA03CKnwNv22pvOtmiUNbTtOTO5FJ0KwazefV93rAL8eLJHdpv1BD97w059Kb0OQDE35gSgoaBtz77STN2+5ocjFt2N4c3zCE0MivgXD05ujD9wQpMI79Ku6DzSOo+yKjtZeQ2eBIpl2xV+o6bwwSZBCDE3nWfefvTi+X6K5HZvKZkwxDJ5KMeaAH7EZdQyF2D0q8X2XyRB+CMJUdws+12TSOQ1Al2hu7T0EQfNqMQ5qyJjNiAbBo5kreQ/MVjUGYaRZ8fAemK13DMJIsxaSdvD40kpRSKsYunu4UBDUovoOlNj6qh6Iah9rGDqWbxcopXt7drWCYvAP1kv6vzx9OH6ntOlqgXh3cXZ+fTG3DXYeZgWRJcWJb/2tFu4YqWKrIF2Z5iO1mnFsteDoLIwFNhU19oqy88EsBf/+++9qUlKAgZw8D9MwdCy1FFsTx4pvFIkH9lxIldWZ7kSqeraTOMQOLyyk2dNE2rjYubIzx70aCyolyO/4Cf53j3urz3fnp69fvz/L9iO5FpmWK8bTgJzrwFADV38A4qDEkeOz7VBsL1uPFMM30RUuSSyf+FdyS8J5/ONyovo/GrWOPQ+kxym0JDog3Ls+OtqKnVilLY6+a6fZKhtEFPxM0XemJwzZ2tV8I/1ANvOkOegBH2+iapaaPpINapyT8rUaCa40YLBU2NK8jByYCBiq5pnSY3wBRTHFtYM1e6/5IAO6jsJQ4mKQ9StJZFxpQO5NJCQI0JKz48oJzdTt6vqJBKg2pm/jIhh5W1+TdOBXqycWnIbLmckyggos1ZFsMpJh03Zr1XSg1I2GLuiRCCKp4SvftSAnVHy02wKPcQgSIRi95EwVfjktivyOex34IXyKwszxX6gg6HfDnaDpX6/BZMdl0kMl1K8LHSepdF/lUFENd+0NFVe962O4nCTadk8BlOGAmUktBzZiLdYjBX8dm9PFG9/GZXOPMe+gCBxjmeb3bo2W1NbJ4Shp51nQzvvSBqW6/HW5uoA5d/Pty+VX9fvyQl3eLH66WC1ppZxffP7+Vb34ck2b4Przxfnqapmq/HJ5dYG3Hx81K0Lv7+//z2+RG/7fZLX4EC3lHGbbC4d6eogq+YxW7c3t6vL68v9dqKvLb78u7n69XalnS2rQy8urs89L9fbu5ufL5eXNN/TX6mZxc6X+fFxCf0wt8UpNLYGsnqEaJi0ndXsHaa4uf76gzsHl5S9foaGvj4+Pr7+uPp/RM7hUl5d4T3CYAZLkn4/GCfiber34rl58O/t8daF+uTpb/qh+PltenKsXf7tYfF/B3GIhf3FzfQ3zPZZ/fXN+wUYorgN3Z+eXN+rnm7O7cwxd/Rm1LlzEQ8kngwtsLOLb2XWZfFwR012dftUyk3p38TNB6NnRSW953y5WKLdub75dfFupl98WV9/PL85pBajqcnW2ulzAhFeX38pEcTwYHT4wHct0qv1pM6a7s2ucryVhR09H+verXjKWsP2qyDjZ6EdHPcSQ6szl7fV39ez2kr7FuEqE4PqrImjXWScyrHQl3QgGNEbC97O7gU1oYoxYDKzg34cCiZuI27OvF0mG9c2amy9frm7OzlFB/uXm7idUIBc/0bfmdS8NCp0J+5seZaBYki6/rS7uvpwtqNmuzqClL+D44wr9t9i4Duh+6C3zN/X26mz15ebuemAjGBf7X5d3qwXsai+WsIkZJklVf7k4+6mUVlXh5NE311EIVPVPf9oD7eHPf+5RJ3+5/HI5ouWjaeCPjk5YN/Bv+8mLx3/fvsPW8PwndfUjcjhTr24WZ7BNWt3coVp3e4OL47Kk7qQH4NyGi7PV2dXN1zyr6WTcrVZ4VIdHmMX2mhpEFtxPXV4samOY2GT5R0QTJu4xX0ouf1u9Oj8gfua4cHZC82EQGvp//Vfrl3QTNYpr1MgIqPjYlY9C17VuvMTm6MelAb/Kn84jfY7WZ6AQH1vexY9bvpqjL2zzdxwxrpRZBlhH1Q1MDvr1pycVHUI1NN8o6Yf5U2skafSjX/pOM512ANlnc92LyopdPwRPh/bpFMo3FeUb7/H0MKju3/BRbblaqGprszxYdDfhZoj++M7GduXJvY7xP0vdN72wpPw/UGh7oIeKFoXuFjhK/CVauVSX7mJuVf1zORTITeTo6KEaAPxvUEIY+lF1AM0Bg6GFGlP9PTLH0RxX1VXYHolg7tpmqG582Pypnov3awSAgAYATzrwRGU/1O+HoTlxxqeOx9eah3uh6XnrDT3Bhw/8de813zGdbTDXLEsA9Uw9eAp9TSQADxiag9YLSt2SZgVTgkB78PhUXzAQhq09ANRtQEn2HA3KQs3fgrCKo+Gz2pjg0IZPfug3MhgJIdxF9roCInnGX3l1WHJowyc/JIOTQ+P47SQgiAMUCAU9P4TPf+gxWKkpyVudTjz5p01N1CGcUPxA2061yE9OWdGBQTHAm0bPMSDqITRjSKQO7HDjuIfxUyGAGnp0DKv4brqylLZ2arXLOfwFP5nWTHzRDLJLvS88/CV5Jsg23BD1sU/jlP3whm7CztAyPLH0sUnzjOlwg94d5u+mNdBkwPpYq32Oe7hJ3wuz2uQAe9W/9jnq4QZ9cIg/OMw+mLhaTgWRPL9s+Kx54Wfces9IVHjFo7becQhHukAPfkBv5/jPKbCkk3A1/q3amldG9bdE3v2rQzhR/+E//nTzfXX7faWeX979WfmPP93e3fz3xWKF9kL+PMeJxxS8Gmoz0Ak3L2GxV2YQZqLz3hGOriInCoBx6GmouNVKWqeIjnzoTF/th5TcCD1Ms3OD8MXZph9XyGwee3vOTQPAP1+fxIyNcB6f7DPWkWkZeA15vnWieaHVQaFOqyYpCKx8HX80RzabY/9VdOmdbNbrTE+87Kvl+01yT/ChBZxtuPuhuq/GO7fQZKhPfhW//98cG51j8V4izq1kn6OaAYm/sOuVx9KBud9+OH5nHx8f29twPXCy0dAR9W62IvhD9Xw4aNioeCmmp01/sWaHh1u9YehGlxyWJDQnO/T3T1DO1kbu6Gyb+Ymsxb+FTgYWVO0z+jat6ZaxsbRtIKBssM7cYS1lD7slX6eW+3exW60FQaFi7DWTsc8T/JGJO9yb4e6wHvZJkrrRV5xu+npkab4BPOAYwNGfh+3nyMPIga2iUZsh0e/GjKmBDGjktblH1nxSkk4a/3r16a9PtoU+BT4K6AU/Pp7HHuAA3YthOlv46Pvqy+H7+4O/xgLSTj5z54n0ue0aEaxR+H6N+QKf6LmNP7uFNv6MgWexwubY7Qmmh5I84IfPSx3+CwVlw4ei6T0oADNfhsD7C4Rf+j0RJSO+rGkJwhBv5PXgovBDNcbEHGFFegJsaJZX70ZOllFITXE5hN5c93U1OZOi+7FGVFZgpmXVAD7KYpGRm63ivbflsnUwO1heXt9eXS4uV7+qy9V35Mp/e3dze3G3urxYHnw8+Nf9QSEm3sd7+OAejnS1RwDLq6s//Kz5JjqlFaDHH9F/0Afof7AF8Ez4lfFw5erxwnPy4mP6xxboDy46raiezk/nJ+njWfoHOiF149XT1QbayfM/4v9AAQfJbWQvBvIfMCti7cipI4CW/3tuemBASShjZ1kBw8e3ELm4dCRnutWkXqu4pQzQvTswieubW9PRrCSNE1kWfJrUEPjgeIbFhHAggn69f3N69Obo3fGHP2a9IHzxAUDHMvOLqHrrPjw5Pn77/uT1yZs3PZVD/vjss2oBQ9VHIDh+c3L0+uj96bujngjuVhfqeTwxRNcgD1P+9vj0zeu3bz+87U8fxwVKqEc+Lr2DQHw4Pnp7+v7ozesREEI/voR0SAE4en385sPpyXFP9Z7pjMv3k3dHR+/fvTsZwDsueXGwFnUkkOPj07enx69hDRyJYx06R2OAnL4+OTl+8/bklBZHujlQBWLi22v0+JqQ/hlzCjPm+M3R6Xt2OIY1iycQxsmbt+8G40BN00hjHB99eP/u9fvjt9TtY8uWzQAbnEITfHj9jrprKNggC0igwq5Vs9xhpfLk5N3ro5PjkyEI0sPf+KD/2OJw+v7Du/fHH15TNxcpkNqYrr/ut6/fnLx9/+7N6R//OPjj/wOtJ8gt=END_SIMPLICITY_STUDIO_METADATA
