set(SDK_PATH "/Volumes/Resources/git/gsdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.3")

add_library(slc_blinky OBJECT
    "${SDK_PATH}/../stash/wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/src/sl_si91x_button.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/src/sl_si91x_led.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_sysrtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/src/sl_sleeptimer_hal_si91x_sysrtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/src/sl_si91x_driver_gpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/src/sl_si91x_peripheral_gpio.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "../../../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "../../../../../examples/platform/silabs/syscalls_stubs.cpp"
    "../../../../../src/lib/support/Base64.cpp"
    "../../../../../src/lib/support/BytesToHex.cpp"
    "../../../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "../../../../../src/platform/silabs/Logging.cpp"
    "../../../../../src/platform/silabs/SilabsConfig.cpp"
    "../../../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "../../../../../src/setup_payload/Base38Encode.cpp"
    "../../../../../third_party/mbedtls/repo/library/aes.c"
    "../../../../../third_party/mbedtls/repo/library/asn1parse.c"
    "../../../../../third_party/mbedtls/repo/library/asn1write.c"
    "../../../../../third_party/mbedtls/repo/library/base64.c"
    "../../../../../third_party/mbedtls/repo/library/bignum.c"
    "../../../../../third_party/mbedtls/repo/library/ccm.c"
    "../../../../../third_party/mbedtls/repo/library/cipher.c"
    "../../../../../third_party/mbedtls/repo/library/cipher_wrap.c"
    "../../../../../third_party/mbedtls/repo/library/constant_time.c"
    "../../../../../third_party/mbedtls/repo/library/ctr_drbg.c"
    "../../../../../third_party/mbedtls/repo/library/ecdh.c"
    "../../../../../third_party/mbedtls/repo/library/ecdsa.c"
    "../../../../../third_party/mbedtls/repo/library/ecp.c"
    "../../../../../third_party/mbedtls/repo/library/ecp_curves.c"
    "../../../../../third_party/mbedtls/repo/library/entropy.c"
    "../../../../../third_party/mbedtls/repo/library/hkdf.c"
    "../../../../../third_party/mbedtls/repo/library/hmac_drbg.c"
    "../../../../../third_party/mbedtls/repo/library/md.c"
    "../../../../../third_party/mbedtls/repo/library/pem.c"
    "../../../../../third_party/mbedtls/repo/library/pkcs5.c"
    "../../../../../third_party/mbedtls/repo/library/platform.c"
    "../../../../../third_party/mbedtls/repo/library/sha256.c"
    "../../../../../third_party/mbedtls/repo/library/sha512.c"
    "../../../../../third_party/mbedtls/repo/library/x509.c"
    "../../../../../third_party/mbedtls/repo/library/x509_create.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "../../../app.cpp"
    "../../../main.cpp"
    "../../../si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
    "../autogen/sl_si91x_button_instances.c"
    "../autogen/sl_si91x_led_instances.c"
)

target_include_directories(slc_blinky PUBLIC
   "../config"
   "../autogen"
   "../../.."
   "../../../../../examples"
   "../../../../../examples/platform/silabs"
   "../../../../../src"
   "../../../../../src/platform/silabs/SiWx917"
   "../../../../../src/include"
   "../../../../../zzz_generated/app-common"
   "../../../../../third_party/nlassert/repo/include"
   "../../../../../third_party/nlio/repo/include"
   "../../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/inc"
   "../../../../../third_party/mbedtls/repo/library"
   "../../../../../third_party/mbedtls/repo/include"
   "../../../../../src/lib/support"
   "../../../../../src/platform/silabs"
   "../../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../stash/wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_api/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/unified_peripheral_drivers/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/button/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/hardware_drivers/led/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/sleeptimer/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../stash/wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../stash/wifi_sdk/resources/certificates"
    "${SDK_PATH}/../stash/wifi_sdk/resources/html"
    "${SDK_PATH}/../stash/wifi_sdk/resources/other"
    "${SDK_PATH}/../stash/wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_blinky PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=1
    SL_MBEDTLS_USE_TINYCRYPT=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A06"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SL_SI91X_BOARD_INIT=1
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SI91X_PLATFORM=1
    SI91X_SYSRTC_PRESENT=1
    SL_SLEEP_TIMER=1
    __WEAK=__attribute__((weak))
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_blinky PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_blinky PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_blinky PROPERTY C_STANDARD 99)
set_property(TARGET slc_blinky PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_blinky PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_blinky INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:blinky>/blinky.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQtz4ziWJfxXMhwTX8zsyqLtdD63qjucsjPL2+m0w1JWTe14gkGRkMQxX8WHZVdH//cPD74JkgAJgMqe6d2ptEjinnMv3sDFxd+P7u5v/+/VYqXf396ujj4e/f3h6P7q68Xq+tcrvfzq4ejjw9F8/nD0j6NZnmZ5+/1+cbWEyX7667PrvHoCYWT73s8PR6fzk4ejV8Azfcv2tvDB99Xn4/cPR3/9y4P3UxD6/wXM+BVM4kUfXd8CDvxiF8fBR03b7/fzyHaMdTQ3fVeLIm0ZJ5btz4HphwAKhakDEMYvSxP+C9Ol0h6OoOhXr37a+I4Fwlee4aKXpu9t7G36Dr21HZC9W159+XJ1r9+vVvoCfjbfQeFJaMM36KuP2q++k7gg0u5B5CehCf/a2rHmGnEMQi0EDjAioEH0Jxspra0d23t80Ywk9rXI/nD6TiPgGgVHo/GJHN0DsW6BjZE4sf5kOAmIpLFqRaNy+xwCcL+6XS5wYmmkmjBtlkLJnnUHWLopl1ILFpXX/epKvwRPtgl0KEEapSZMm5XWvhFmrJPQiKFYmYZqgetlF4e+o4RXBkRlFNie7MJUhegu2+skjn1PV8CqG5KJ5Tr2TlTTrGGy8jydgOcpC08HgCC2XRCqIEgD67ZgFBvmI/z7T6DMgFRIKkvgOvZaRyME2KOtk61sih14hN9PGhmI0AYlSNwWePRRSb302B60ggeZzk3RuqQ8GgW2AslUrYoUwg3eT5JplKDSjA08HnryDdjAo9JDckCInuhLfzF3LFm8KECtg6uF7wa+B7xYop2aOG3ZZ2Zf6aYRG44vobkpZR4VrY0aeEIf7gzPckAolVYDiY2SzFrYQGqjZPtRHALDTb+VW/loYMzEZJqLBtZLzPbsWFGr1YFJpTk3QzPrj+Gfspg1YPo7/r0dAZjCA2b8Wo+sR/31/DVaKMm1qK1dZI1Q/kXjGwtPA0vvG1+QtZTKF5RvYL9Q+6TxkWsmjU8onENA+ar53c4OqN81uSHTUj9sfGrf3XzXYdZtWxPQk1h+3I5BEpWKVxjZevQSxcBNcx9PwtmKGSy60U7b2xsbZb9W5LBGMlIjuYVL2rMGLa4hg2rIWho0hJZrqOXEtVY+GqtGduAmuhHYrM2MDC0qHNqZV2oX/+tKa0ZshkkqUrwO2aZnlWdshHESqCVax2RiikpiEOkhbKo3iWcq4kpBZWZrwVkwngrrka+SbwOXzrizONdbMq+rnazpDcLQZx0WjtEXktIqeEw5s4ZdsB6/BMzjirEUq4BMHC04BlfKsQrIxPF+efoM/6eIYAmNuf6ZZoDmNS7zsrSIwlgFZecKZahkmcINannV0ayhMrOtjFgU8m3gMjGGKQiEIqYVPFaGSitSBY+VoRFFIIzVMSzweGqR8jJZwWQbE5YHkmqI1iHZeOIFR6VVpw7JwdN9UtXAV/C4x35drzrdHzq/7Z5o16qJB7WEUzjbD+3YBnn5lTuCTneH0jF0O4VBg2nKyCSJePfixmnWgtuiDmOWqCLeDk/jz1OEUS8joQjjfTvZJRZxL836UkS2Nqm6C+qvkZcTlGE6RgiU8e5loXjmSmwouVBj7bPeOUcU1063v6it7oY2cqljWlB1IzvSSQK2yrK4WV4vWZdWL7sEU76/9kwnsehLwUWSUt4SALTxJnMMmxpUK1tLw4bQCAEtJa41+DCvpmYpL74dkBqEDK8OV6tfDkeHlMwAHfSbi8VB6ZERGqLL3S+/H5YuKSFeXT47kN3haJLT4dXj+uyAylZKhleHm8X14eiQkuHV4dvFt8vDUSJjw6vF8uKAciIlw63D3SHpcDdIh+/Li/vV4WiR0+HX49MhafFpoA4HVLMzNgO0OKDBVMZGzk47z+yvc4lKxPkKQdbsPXvBZYLDmPkwTnIqdK+UD6avOkfLFXJflPc9Xzo7mAo55SPFztFghZryAWDnIK9CDU4v9K8X396/Oz+7UMuxjsxAVvnwrXOIVqWmumawV4zvlzeKszZDZCGnfiTYM9qr0VM8wOscxDWzVdY6dXu2tq9JN7NVLbsMctyGSOi7XOu8XMvrSLjpPMpzasosU2iRL7SXsZn361EisA1sfyrGOTi7i4FhPtqevE2MDsIlaC4Lm6E8n6K+EhHyORbhNPJ8TPrY8nmb4AK0SSJ5zhF9pTcD56K8sd2pCKfQXHS3geUaUxHOwbkoB/4eTswi42myklFlwEd+P1nxSKG56P4RBfZUfDNsLsLhNJ1HCZqLbmysHaDLdkbuId4gMUAFue52TArwud/ladFB/8mIZ+BclJMJm+xkSIuNEun70AiC6Uxd58CngBNEERqAT8a+TECiUyQ0jh3sQGg4KQu6g81w7zLT8c1HPQksI5bnqJUZs6kN9tuqc2A/5hDKOwjVw7kEz0yXTL8mJJwT4Dn6EMaTGrlgwEwat+LyDogykC4YMJPGDfmElDN8LsJ5Az4x8TIPdgUiI4wnZZ4RUOiXWmlrZXeeFN1RJ1rnwNXeT8S5BM/Z3k9ImG+9z0ie9RBsQAg8E+hPvhPL9svvUaGTEHMuGNakhSaF5zhmKn+C31XGTb45PkI1QiOWeESbhXWFBTt5+WuvXaT51l9N5kBSktjybXZYxqTVLoVnb6uVrGx3tdXcq9vA26HgQpaSJe4u5jUezApMzJuXrpql+Q7C/MvzWxXLxV2MeZeM7bNJW40UnoPupG1yCs9Od9JO2ubrnP3AcOWdcWbgmxNg3y1XsJnUQZh3Q+kPMGnjkMKz0524MePe/0IJUOyweNJJYJUF+zK7go27Dtbcm3dTd84hd+ccWbYv/1RZB+WcAAdlF0zaxOUE2ClPuwQTcTpcRa49bZlI8dkJT9so87bJ0dR8uQmT/Y8pKecMOEnrO2BYaB9kcvJlJrzbSBOSLxjwbSNNSJnbH0GpL0IP8UH+CGQXZ0rmGQFmyk+GNSXhFJ6Z7j4J5bsydfDN8PlC4bjnejBZ69FkIdFJJfEgcWChkMiCvVNyNYhuuhIHipI61bBCNRIKd22pFGQXrbIdKmWqRoK1WkzMnYm10Pog3Xkrz5ESktIq0uLc0MVrilpTp6Gq9PU1zhRefH3MQWkzXAXZ4WCHaNIbMlZIU7EzQmtvoJu5eBoIcq0Uazy0ruakLVcIgvR2pK6+RnCrjUjBpbVk9V2lwNx+9NhDdgFts0eldBZcBtmDp6l1gCWzlEHx6osYBK2Wr5TFdIULEVBespAZKsUqZSG6TLG3hREIkQ5sTaD35L6WWTRJ669vUKg13fbijfSCmqqvIc2qBZTKpSMaDlUhJFbfwR4Pi5lQmyYR5TUPU8huk1bk41gxCKp4LSR487VZOJRr0s1FeidV3A8rqUEo7p9FxZaoquhgRGbrgkNembpZTdCb2TVOygpiyTikONKYTNiv4dsIHPAEHAlRMNa+/MFDSYN8UTTFZfcHjRQd7aSRLYOze0sFbjIJ2wyY3e/IUVDZKERTXHaeExmU257qIhpQ6Q4LZxCEPuQT+TAp8CIFDvlU7hQS7E48YKvEn4BGvITNwTeGeLaChQE64xI6O2cFzgRUtpwuBFBAMGVBruFzeQ3gBcaJ+uUaPvs2trIj9TTWDOfpaRvDe0v+zjuNbgY8fjOD6xoYPDCQPuUo6ZudVM2AuUYkUxBNcYf09JPQrcBzteFT0OU+iF9qQ6fgW8Mf1IZPwruKP6ANn4J1BZ2vDZ+CbgYsbnev5UXb42pHsLdD4MCRc/+99S5w/fCl5aKlknVdw3F8U18nmw2QFA4jI60RTloTsmld1gulQBh6Pst1Uu1dKH3FFAuWaw4MUV32zlHHRVRtXxuqKEvQZAyNajri20szMC7VWMsBtKAHYhkFAYpFq9Qg9NACKrozTm6pIJrUdkOoHBiCAhNhOm54Y9ux4xeV5CnQ7JyJ5kjrbWigCay+MzzLkRRGpkODTiJs+hS5aIbAQvNxw5Hc1rYVoxoBJe0MpShIbXRS3dNdJwq0iFKoWINOIpz6TMJdWtNvm27QP85JqQQoWLTUiofoaDU0qt5t7KRmToMdNVdYTb+xQxf7iyQBLJUtt2NWFK2lwCVZbn7UOdYf5BR6M4maUGpusXEflYVtw6Euz3LJPVfTm561Dqkb5xCODIObFn8MOAVao+uHNyF8s/dD2YPKiqcQFXx4EYp3ITAs2JiwFCQ7O3KSOLFNUkry78uVz/lpHfDD1d/5Uay7ZsI0+UDgTEMme//84fSdHsGJsmcGOgKRa6VMjfR5GwEpXbixW5P5zcZoce0bNolD9RP5vUC10BknWNzl2rCiR76G1GTANl4LHCPe+KFyzjVoPrJ6JnhC1hUOPDO0dTIF7Qo2E13UiuXVUz3jBjwD6XpF8Cevij5H6SZZRLyDpiogObqSOXsaMFHWgZsWhUuhGtkvcCSR/GJDj18CIOcwbQ/dKjorZTK0nYJujsxI1T2fgiZBZaToT5LxPk+GB49wgLV15Tgj9BAtYzPSTaJpSmeGy0hzb0cANen52ZUIxImckHA9xNuZsKriGF7mHi/xwEGfGlQWPCpYYGN707TEdfwBwynFrCnwnKTleUwz0u7xmm4c8cdI6gmXgOUsRLeMrLpWqeQu9nqNVao23emrVL4HkT1JIaXrNCmYPFTRoihW0pbd8tT41oHZSasYAVJicvCRxOtCeVVSSLYJzE7a9mPUmD4CyYOtCuEqKDtZHHbT9B0V85dqZIkGMDtpFC90ivahgctBOTbiRCnXHJCdpOoywJX1GEpF951SrOExr9FTH1MeNh41H/SfPq+fOQcx2lLRXcMzto3Tpgzr2LSN4bUR2aZQ55H8fG6VbtnxhQpaz4N2trB1Qe8UUi0jsvM0QRhDVNOI4Ywtht25QtvSoBmYK2DYZEKvVCz7W+2OKNL0IHtYNSh+fWhDepo24nrCNo1K7jSd3R+NneUp4ZXCsDCyA0EdHQOtMhYLN2XEuFhhDGXUqmgsLZJ8Uk0mLD16o0qvIysdpXd3zb1VH1Ky1sL0LmiRuB+Z8E7bw69s4hsskUcJgYXMW/jtW8l0cozukgnHkgIu72qhUkjvJiFmFtpGonW6WSXxIq7VqDN46W8iEgHxB1vgE1o0QREj/bVvhFbXOJ9MXEYO70mMDIg0eiSEpeSzqTALv5GKljDyKeSPzdoK9SJySCq6s2TlX6Y7FUkoxiuznVITqK93xHEiJVmqIb6PjH1mSuRSkd5HJdi7EqlUpPdRiaTmUMSTQelVBBLZ1ADEN53ZsmJX64nYjl8awTpL8KXNNMAvs0lxB5isiTKCFK1MNjPOZMuZFLcZa2yJripTXiakg/VVN5JU2Oy9gx7PpB2nELzx0k6tf6OFyk/MZLSdFvP0E5dkaTzktJHEv6JzfNlo/+p6izrpQLhkzVzLeYb+iXWzWagTNizLRqMmcohVxF5MSj3NLqp8rZOS6UZ2JGw3vkqnIbuHirBWqEajveVpjA4BAO9PzgRV7SqNhuweKqJWCGssWhcD22qXWPyW0tDXftR/VmtemFEp1b96e1PsNES1VqektrFHoTlsyLu8NTEPgDs3h15flJPTyhy0fiiNgWUQ2k9o8+QRvOCk6F9JLFugOllCkHBjAwfOGg2cSDQ3GkA7oz+TEOhrw4ltF3mtyODUCtHKyjSQBOFMqmLb0XHmymHQEN3DIitZ4kmUJLdyQAtsIJRiiaboHhYyLNGQ3MoBScJOyKIp1AW3WwHP2Mvto3hztEIwspKSR20IrZzcFws8PdpxvQ8RyaoDo5eXDCtRZPflmbVFEmS0+G0ArYyAEQgnUZKptQ2hGkOiXezWl6hKNB1/O3RXrSCJILRcUqtJdsBx/L0fOgNX/GqAVXGtqHDG+2RHcLo0OOhEDbcukD0r/HhX85SqMLU9CzzPEcZYnhhIq8prpVn5Wf1Rpb8F5qOPkPTz+fm8uHGkvi6aHk/tGKX3rgowTLJj37VZTzFskXkyXvXZdC6oe6K0tllnBl1oqRSW2bofnfEdTezCpYnsJGGXkoDnWIdF7RHFhbajmNmXu4NQr/huCwEvYW1au6ySiekGM6IIME8LO4taLqhviURUrrPlNZxfheytYxdgIagH0IEZLQIvk9OnH8cyXLd+tPW2/kXD3lXO7vrAtvRJJZ4dZe8Rz1QDRtMoCWIqkOMBC0EsBVIAXiaHZ9mrUVwWN8vrZVf/uPDDegCR2hfXnukklFBV1Qk5LhRoFc9mj/VWVR9T1RAfLYXUmlI7tzbI5yg0LbtLAyOHktBOCvGfaPk4hjVDFH5VIoP+W3PYYKZV91RgNzRevGI+9t6PXJLXCewGiW6E7tM7UcgVgQLcJ+9Xt8szYTUMNrsjFMVcarmbSuw0so8u+jFZN6P7kUvy+HfTlxiq21gQAAWntpljz7ZzJnBaVaL4/U2GgzLkXI9ue3aPJy6LJ0hJmO7BPwfZKfMxLAnLui+afDmeEw2kIaWUpknlEHRVvoB2wfbhiAIY7viszCSNysJMSJZ/ZaG9PnLpt3oYDxv59JHIBMspQLmqYwpOTj3bNy0J5bKfDBKZYAHFlsT8H19oiRxcq0YVGSInHzRXpTL4DqLPH0HoAdabVThoFHLlFNyytmOKTUq+8HcsS+WzoXAahVwRhbftTtMhBTiXNa7gdFxBylCE7WG3gzJyoUmXVJQLpQVpkK/rlAVzWFMsj7pk8QNI4FrhU9fwkbJWzp9VwPQtVtfKqmkwv/IiWC5KQMWm3FvOfTrtqbg4eoSC1Iuoe4se+lgUKBOYvgUeCAcOlmmaluT1gw9tqGjALRcRU0HTy9EFQhcS+wk4/sApNA07EzbAk76vc6tdoY7jmjm29ziwpyuxR71Kt3RGK4rikQnjt6Jjr7utCD/AEIubc7yCZoyjDMVpFJEy+pG6anw7EHDMZrLHhKjri9REuVOSItSpOpM7rBoidrjrKqR0bAakX41samuYbQ3tOIdY5GXbvsse7+zQ0gMjjF+6CsYmBCCM/Z4jnnjVkVJ1WNb4WpdEOQobUlUraaRltMl6aLbeV5HdaJWY7p5rW9ataZHh867t9imSLbbW5VOCAlHpuIHvc3XT3IRyBCb7srTKZLbYV7oCP4yNtUPPmcqXXxYLluj6F/c3qFH+zBInGoGLKa9EWS3TRoNktYyJlsEwRJhEn7qGGbKeOR9LK8eSElTyBrg3BsvVGjtgBPq5nKxISWgFxrhQXLRujqVt4fdt6tUxRdbavJ0aHGBmJygIhRQWZeE9PCwQhAC5P1ok3i0++cTlysHMqh2qhyN4Qn68W6hUIIdZHaCHz2coBm2DSeFSFt7Dg9fJh5kD3eungQ9hImML0itYpTBpQvRxChISkJLn2BcnpwYEA6d9aAQBuqdWFqMyQA+frEGWwqUsvI9H6P8XbAnk2KQsvIfHHwlI5Bgjl9zDIAJusJNTgwrRfRzQhbA6HobIyZE6QA+fJfr8Rh6dmvxe6+AtQ4lNXQOhhxHyMZRCJBPch49W7eVkTSGaeY5JG1qJHMSWhXYux1XGEiIZ1AV3suB1t+xFp/ldtjSkImFzid17VJWqIxK/IbnbzxHWHLGZnkvsxiX1RShwLlLEDjPY9scwxjvbTzbY9y6DXX35cnXfN8kjX+n3q9UouxDqWsFOI4K1qvy+vgx/PKqt7CHC0qEWjCUSyeQPXb3iWrKtHacqz/GDYG4GAZOerhHHUCMUNNyIQHEATVujLZgXLZelNXFcw/aEARXCKEgo5NI7YVAlaRSsC5gYncWACf7GHAuhBgmeDTdw4LvCD4BEECu4NGF6udys0UWrw4zAzagAo/C6yxItdobH7uXDz4kGxMAHt0zSDNWK1sXsykPeDazD5xGkSkAsfBSYqQLVxemGRCyWb6MSEAsfBTaqQHVxukujbMk3UhmJhdGvpyoMVUdjYnamlNlZP7Nl7Icwv+VnYgmIgc8Xro3p8bS+1Leuu62lIBMrUAycFkkUo2twlTErAzLwu0z9zdQRrCBSGH6Cct+yHgur0UGOINghJAnQWqtWyGoHGqh5C1SrVi9w8LTyf0FREYTAVeR1A4rSsCaRArr45fruq7/dsp/o7sF0iDCtJpgCvQLP8a3nvGRfCVI6I0AVT6GxxMV/wXO1KIVBvTbVpfYBj1C+E7pNawFGr+P2GRrVt9fvydBxuKHx/bFw8v7i+Ial1WX2wY5QtwO4q3LdpVa6Aa4fDpx81os4XS5tlv0SoRDAKCZeso6Edxk08RQWBvN9VzXg8kKNC2evsRPBd4GPjBEa4YtmlO+1qmJG3ilMGLEu4HIjl+W34O9DO5aJn8un4K/Tzk0KeCGchmxvUaAUSci5cAqyacqCTSXTMO1gx7xKzw2bC29FxjvlUuFzBBqHNIwuvu1YFos6Bo1HHOpWuGaNAcJNoSSegg5MaycJORNNR40MebBENhVXVnlLJdMxdTMJn6R1JFUAGgMvDv2ANa44N3whnYK9e7Q2koAz0TRU1zBlVqqKfNpeBOv9P7zArtWCiOMsS4FMJdMwH83ojSzUTDYNNx3KyYIuiaeNS3fG2Zu3krAL4XTkN6eshwkGIKfCKcjPb04+SMLNRLegoutqDWkj0RoCtfVmDT3SgZ1OOcgXejYTShNkxGLbezHDl4CEKElx6Yx0EX32MFJ6R58OX4ro1YcSa+/1w9AXMMwdwitDprDybQGdxABOKS61PZ+EUPDYykfQDGEQqa65Q/AoaH4+iFnX3D14FDRzH8Ssa1afdav4yoxp+NUZtPc5rC57YgmWwVu4YQvrZjRNe9Zg0LJwuEAp/LuLryuYHP8Qu0j82/OH03daFxKF2P3VxeXN1dy1hLjtlKSlWJWLJDPQdP8JQkLqwKk8wVf2LXw3gCnW+BoZtAQVWuevX783Pp7M0f+7ODl7hR6dnJwVj97CxCgP62ldM5kbcOC637jzyN5voZHc09NTdxuv0fHu2Pcdc2fYXj0dfBdZj/Wnpo+kIIvP4ds5dhqfw2ICwo84LPZc//D63cmHt28+nBQRsl3fAs5HC0RmaAfIEH/5SWs+Ix5jFYPBZz/howLAjOHfR7Oj5fXN3dfrxfXqd325+n55favf3F5+/3q1PPp49B9/h5ZKbAcWz6tn7KocPRx9/I//nKHLc1z/CcBs+bgxnAjM8g/JyVn8HV79gdj5GZ9is2OWv7tfXemXJLga8tCqvCs87HSUtPoSH4omp6EtsE626RWj1Y8C26M+R6Gz6feS0r+Bk2+n8Rbf3p7GMHgynIQcjql8gu8N1NdJHPuevo69kzY29Q9PmT7sUI985wCr+wNySCGy/wSt3xXBf4ovUBGABS5Bx2c/Phz9lBapjzc3+OGrZ9fxoo/p058fHtC9AXHwUdP2+31W3GHJ16II7SWjj+YAZSX68lVaknCyOEzIQ9vCvxNzTnDneLdlnphpoSINxnxrmvjzwHIr6f/ygGsD9rhHDUwEqzZqegjK/H+h/2roo7x6ZLr8Bdsj5QS1RRL/MRtbM4wk9rfAw8V/kV97lRo/e0kiYqD2U1/6i7ljVd6SgNwkpW4aseH425oAFJMcu9HvDM9yyEJx1+tG6jx2HPkiagpofNEuAwdPtPFarUn7sFK0i+8akC3ftchDVaBXWPWjwyrgK+Civhn8aEW86e06a/dundG2YesPd/mjzCtjVvYtmTU9JGZ1L41Z99Bp1vB3mLVt0s5qW+Qzuoss5XHuOzpr882kvajJqjgP0l7Uvi979tGeZ7511HdnzXcVpynaix31cdmVifK64khEeV9yHptVxpozmrdE/SFJRXX7mOWb0LOSM/2stk08q23bzsrbqLPyzuYs32yclbcAZ41duRllj2xW3a+a5Qtks/LC1KyyGjQrdplmpa2fWb4dM6tvkswqexaz0grOrHE5C2eA9kEC0gjjg9KWIrPzpi/FGOdMWgkSzpm2GtC9P3FH0G7exKW426xJ03A41fDXXYnbLirhSJNHlmBPk96Gw56Ado0NR+oBabIrYthT5HeScCTJrxXhSRMWPR5bmt5LdxgkNS7yYE+T343BkSS/voM5Te9VJ12S2sNd9qdqhHPkTFIOO8mbdFvpZrmSppEYByQroijyJs7CIDKma4mix5i6P3whr6As/mB3OkrYOa4E7JlKCb/XlYAzaj6vqI6rBFhEdYVkH5M+i6bOJYMSVn9M+iwiPouMvqDIg2TUAxpzCqHGuh4kgxajmklQV9DzwQKKcOUcIujB6wcLKMLOU0QMD9InQlj7uHVIWEYuMZToFkPS12NTDJFBC4A1Rk4tvssYUZ1j70FR2cbIaY+jNkZqPQbaGFkdI/QRkb9GSWvE7BorrRxva4yscrysUXJK8a7GyMlDVo0RUgSdGiWlFjBqnKxadKUxwrIISaNk5DGOhkjpmOqNDI0qVmIe1XSU2Gbg0CHi8lhCQxI3AgENEZJH8xmUOI/Iw5KaIVyMADFZ+BtRogirzMV6VnOpnpXDrcwyf+dZ7tQ2yx2SZ5lb2azizzUreQ/PKv5Us4oP06zq7TujuBHNyi65s7KX7KwSqmVGP1IGH+/tCJi+5wEzfo3t9nr+en6i5VuYkYZ32zP3EzSiDiObbMGnhhojgrrTP0AgHGFvA9sfywvN4s5MAVKCvStASiREI5jzYTxKKTSHKXLdZBRRWzm2LDxENGoLobxyyCwDVQA7fhkqI93aGcrBBgC8PznTy8M4bhnBqOQDDZDORrPUrFlJlnny4oA25zXXTPA2jWbu7ADTul+ePsP/MXNik4q28jhNxSbYMmJDimA4z6/srQiUW9ncECiXfChYLmoyTLS5KYM0Fg5/SBBLdlzFyw2iqjeXYNkhHBluEs+UID1dvZLCnrj6SCmARLT7JLqQpObArwWKRo2zfXfzHa0RbMlflh/DZ4Gb6EZgRwLb6zasRm5j/0+xuAjDAiDAi8N65JsS5Jfrg1jpcOQQoogSJPcFyy4XLDGii1EDMfs6EVWBixFFIVkk52zlvOQR66+RgxzEMh0j3wIbjYZ9arPOKokqLrVC5aMdMljhbB9O8WwguDdIXYPT7GiBGmsxK7SRU0+61k9+pT4pl+RHtq9AfuqLi2+j9eMHFTPg4Ma9Wv0yCah+c7GYBvjul9/VA38ueSQohL0+m8DIN4tr9aDfLr5dqkddXkyg6vJuAtDvy4v71RSwnyYBnaAsQVRJTbGCLuZKWnP+RVpxl9Y4SmsAYdelf7349v7d+dmFHARpDZq0XPx+eXMhZ4yIJcvhjBtTOaTltdPS2uKuA5zjoXZGaO0NdLgzfUDOexUbFsUZMOmYlflhiimqGDQwHWBVlYQP5GmI0CrqITRRugUgxIddDCfHQ5oZybMegg0IgQcLzZOPfWiFzE97gE3kaasngYVO00nGQlNjwxq/RMoAY5q2Ehh0cj00YgEr1ixooRrbjd86YUIZv/PDAGMZSmwGNkmkpP4AtNOuBMjboZO/lr6xXRV4imC2geUaSoCiQEkTZJ8pKeD2mZLqaitpSP3AcMdvSzEABXslhfoPoKSo/aGoSCMc4qqrAi30pA+yMIyqhieybF/cAm0nkAuUFO9ITY8XubYau6mpRZEqHOzhpg5J3wHDKvympSJWPLSlIiWKWgeEkx1cUIIXGQJcsRiAngxxSwIdMPskHO910oOTLzy453ogtfShZY7KCoDEZY5scxzNYhXAkImSAqC0/VOAVHH/l4qEWyNFOHlrpAIPt0aigELfzRZ+8wG/YT7aAgeUFAj0yHQexbULbRgCV5vaIMT1DC0IYtdl2kCErsm0gIhcH2mBELs20gIS+HsU9NV4kp4tIiffLRBCZ8QtGCLnpy0Q+IidLuoEAROYGPfdPqhSEAZpIEJH7h0YwkftbVhOEEWohxEGlAVloMbiEb3P1QDLR9PEs5WE1NFtL97IwaxsHTYxRQ0+2jFrwYNEA3ZGPCkFGpGC2AiPghVNvZTFDsSJO7gDnsiJ7fQMnrhJJk2+FQlus2gg6ESDVIDAEVgGaPJl8xc/RKHChL4JosiHUMCLBG4h08BCsBW68EjHiGFanqPEg1AELjbS5MMHgYocQRVdR3NVyW2KhP6cgrLfW+Imc2WAbOqOWy0ZbXt+aMlx5MovWhWZMLK6wHwRqlQ9pOKUqodMnKJ6yETB1UMUQOLZGxtY6FRiNsIlr3ShCxEUGDLQkg1WGc2WwUQbsG/9XYqGLKCiTm3zYpfeq9K9ktl1/DEZvrfRFTpRpBm7NZp6gXBjwG9KrntjLdyDICjEQR8KtqNMhDwQuBTpvlTrBI+x7m7dcUOTHgx0aFWmfCQUViY9d1Qmt2DIRHQML1u6ELA8w4KGwxjKqyl5tFx5AMhPZY+uB8OH6hXAjF8paAHKBi1oaQUVPPccHeeX0RjTkHxpSCg0VDWml0wIPftMIhbpNdeJfIxyLGIJKNXKIwQGhKHnkxA76C8xFYUIrViGSBdCeWOHLm7hk2AbGig+cPUBidOmEEqIzXZ+FKPanT4vZbTumYGOXovRyTbdILuELiguNRAtVYhR0k4Jjx84o4mxyM12H3hDrfHIRmUFU7dF9duUWaYEwbg85g2QBADbj1HpfgSChp3VKVp6AZXImUUFADlfyyw4nAEI2QWLN8gezlqFjhtdfFWa5hqOA1s/EklWUN9NWqiMOWqshLctTYjxu/h9wnFF3ZIIpbU7GcUApn153WAi86QE0a6TBMB0OxjCmiGw0NaM4YgtbQ0g3KymYUbzG1zGYoWNrlKk3LQ7g1VyjaJcbeBUB+z9UCz5SpcmRHC8C4FhwfFIOnpG8t3EiW3yguPIctajaKi5Kzd9zPWsVQLNrAKEcvdO7bIGDgbaBfL1QlU56QA5tf6w/EsLXJv1WYVmvhfryErHMsRzB8TWmlm7diE2/L+30O5vBcmCosZKimC94nBIbZPCN+5rk/LCXoRaRCQcy/e5LxGIUSHRXXJfaqkzFihqQPVlEGp5QsVxB4hmkClc4ID2pk1q3vIUozrelqIhMh/1CBSlr43INnUThDFUHt2AA0caPkc0SnaIAUMmZuGwyUZXmPdIDkFELo/WSvpGmrFH+9U2QFecF8/n+N6DvrNW/SIDOEZBZn0EL1jkI+iZPXSIRNFaNzZwLNgTYWGDBP2ZhADaDQ5tXHwx7XBRpoF+Dk+OLSRARGbbIRKAEQxO677AIeWjHdeLzRhZY3RB9QWEowxKRIwigYfX5RolSJQAUtYWPR1T5FEfgTcoOQTsYtfRdsBxfNiKOT3eabVkjr/tG4rVUgTZfea9a6tFQj/e4a7QQjfYQyFpuuc3Jx/SJhX9idrw4lBj+iQu/cS3vehmhKdk/wkfur6VOODh6OPD0U/oNi1I4OPNDX746tl1vOhj+vTnh4eHo10cBx81bb/fz0l+zWFfoMG52R35aA7QIin68tU6sWH75eFkcZiQh7aFfyfmnODOycZu3qEs8c81ukX1Zb41TZwosNyKlL88PHivXv1koxCMyIrRq8CI0SQcfzX/X+i/GvroJ62m0V+wHVJmUGck8R+zv+ePrp5xVMcIvvoPZJwQuP4TsODPDewUQZGWXEGYf3cQRlzg3etUxh2c5H2Cia3/MeYgY6ZHNWB5hCm20f9YcZAVf+zC+HBkJLG/BZ4GR5lmHtI8PKSWMzGz9GpN+59Hs6Pl9c3d1+vF9ep3fbn6fnl9q99d3iyPPh799Feo/8PDK+TtBqF+fjg6nZ88HMEnwDN9tIIHH31ffT5+/3D0V4gJQVNM+IlnuOBnmqILYv+SnkgiTBjA3v9lacJ/YbpM0BGWCz+A//+nje9YICyEk6ysfJN9CecoxXfFJW06Qkd9LnyJr9BGN5H+nJoXPcQXf6MnuDwRW3bKzmbx6ZmwJ8NJyKxWGEJ2p+wi92cSSZ6svzrAKvlLCZPfDCcqknrLVXBSIOLQd4QKD2xPhsVrkU11RTDr2DtRhHMqC6c4mSdTEXIjSWT/CWTAANex18TDAd+sMhLjJ400ueVHNgmZfmfEO/gzCW2kXZxYtv8x63K0rGEmsvKuCP96JadbWQEX+a8BIR1LOmDo71nq5dPGC8QmWR+Dn+VjgMLezUzgrgUFyk4GCuoMJCtShRCpBS7OIXqmL/3F3LEEykbd2SJfNBVt/Hz2rJtGbDj+VjQAuSW95IogT7jgQmP76RXGRL5w0zfky+KPLrwfX/CHNst5s6asXW5fERrcNtOX2KhNdWO6kFVdytctaYgnQ+v3LanI1LAnVWta2EAyJW0R4JoJR/JWW4V9WrPL2tnBQFltNkKT9xECW8TmNxsKEN4Fga5MFAaRAVXanNb7GB+ytgF9/1H71XcSF0Tafb5AvbVjdFdhtMML8KiCsRyXG3FDZLP9FGiHyh2Yk+leYSFKX0onMLWgWr9Xu5VSifnroOOtXdeqfo+nGrXqqML1otx+qkQzCq4U3Ro3xyrTroE8Rj8BlbXZJ3lietOGzfMbsaXbOr/7IUMUXoaq98krUagKKVyj6ilvJRpVIYVrVIoDqESdEp6UNgtdLFyc9ldWiaqwcjSDeGp1SgGl95sqlarhStGtMmZXql0DWbh+UHpxRkqJXhVEGfoobi4qiDL0MaIIENdQVfoUiLLaignqUgVV/JyoPOlSpVYdVLxW5OST2gaiDipJK/dJXfdbQZxs7jMuMbPnyQiZohY1G02O94Qd920/xCfecw8oyflPbpTNZsHtJCafDlPH3cj1WFVLTSzVgjzKPMyFQZ2K7QSGaSq6YqPRzA9SsbGLh/x6jCxSWs1KMcX3TFUXGX+N9gIhnukY5JiUIi17eUzeYKlavyN5Lb1pwJbPowJmmD/aSGFossaOMwkvKWzztXTLu9hmbXGzvF7K2Ia9HE+2U/41cZWQuwNLlNAXsufjWTTScj5rOGs0QkFL1dUajKTuvGZoF98OSnlCR4XmV6tfDknzlI4izfWbi8WBaZ9RUmWBu19+PzQLpJRUWOAzvsHlgPTPCanQ/vrsoEp/SkeF5jeL60PSPKWjQvNvF98uD0n1jI8K3ZcXB5XrKR0lmt8dluZ3yjT/vry4Xx2S7jkhNdp/OizdPynU/KDauYyPIt0PalCf8fln9CmVsVImYNuGWjyo51yVlZB0cb1JYvKFysNZERG6+FFT7GqCye6VgNlsTY0vE4xlvggYsNTUmGDuJWB+VVNigmmUgKlSTYm7X37Xv158e//u/OxCtTZ1bIFqTTDZETChqSuhvq6Lr+rfL2+UF6wMU6QaU8ykhMyWGooonxQJmPjQCpW83eb2QjV2Z5lWqFTrkYEegitHcUu82H1PadvtiLDpPMo8jpHlWmGb4nbiEroUz1cEALLLGafRL4eX49prmI9pKEj16pXApeWeGco839BXNkN5hxywfJle5n26yfM3x8V+k0QyXZj7al0GL03Bje1Op14KLk25bWC5xnTq5fDSFCzdLz6ZllUO8lTdT1hQU3Bpyv0RBfZ02mXo0tQLp+raS+DSlIuNtQN0+Qdoe9Rs0JCssOwjS0zqyjvClONkF+5OpGYGL03BZNIuMpHdQyIAfR8aQTBlNtZZyFPXCSJ0GcHjhLqWKfxoruiZcWsLFzDb7GAHQsNJNR7qZN4iX8o5F9PxzUc9Caz0PgTJxaFpI3wmpM5CTlCEUGZgmh4NSwSkKEeWXiZVL6cgK1BCGE+cgQUHKSriflxmKDUGFQsOUlTEXfmkCmYMpKmXd+GTq1lmIkfdyCDX5kyoZ0ZhcmccFdsYlX5S/uCNYnc0iKuzkNZbT6ZhiYDE3npS9eTt1RjJsx6CDQiBZwL9yXdi+afgexTupCQlhw1r4uKbEpAUOE3FQmRX3TTlrUUihkZoxFJDK7LoWOEhR1UVe3JdKsrblzNjFfv8nbrJ2+q3jIkbl5SAnL5R0W5qV98odUcVeDt0PYGlaFu1S88aEynqTq6lTOVUbR53qCd3A3mrZtOxSz+ZG4/22cQtaUpAknIT94EpATnKTTw8s+UNy/zAcGXGD2TQLqcgx5NPiZtGh3oyXTX+ABM3mCkBOcpN3h1I9UNBwtHtIvHEizNVHnI2gpW423ToKNXlZvphWSh1WBZZtq8i/kuHgjkFSQq6YOJOIqcgR8GpF4Ajia76kWtPXTpTBnLUm7oTlNkHRtNrJ1U9soc/rYI5B4kq6jtgWGgv/wBULXOR6ToxqaoFB3muE5MqKNUPU7EPZo+a0v0wid/CtHpmFKQo+GRY06qXEpCi3D4JVbi1d2iXMZAXJtw914MJW9Qmj38SN+HEg0YCFrqw9AfwD86zgeSNrsjNtGSkatD4Go3/Fl5fVOXlV8xyHlRqZI2GjCZock0F6niAbc8PeVQhL38l9oqboxZH1C5m/71aqLoB1NXdvmEEhZm8sdOB6a5GYfmXIw7RW9AFigfUiO+M0NobIZDTdK+TOB55Q1OLZDGdQnc5JOwV9Aj1TNAIcrU7KNgIqHnCYsfK6RGY8kV+09CWL5V2oWBzEPkio5t3gPWj1mFIfYoKDGGrtTflcRBFpCU7VFRdZIYJ6i3KjkqlTXkcRHYc0GggAiGyrNhBgPfkvv5Rmw8y3tM36EIa3fbijYLGJM0EDdmt2ohQ2QiLJ99iAkRD38FRMYadVP8mlYOowC3lU2J7ig1hgY2RqDwPV8kY1Jy20JBdIpvVYALdu9kcRLmUMRSMHAACvDn9AzbpOXfciJDsUxYKIitBBYu8cevmdRBlqSXDpI4Z7ZplFFbzUiaRyk7jchAZc0ijx5coBq4DnoDzg0RxXvsqpiMlu+Rb7imynBOdkbIgcjTVyvByTusEbjKRbhm0nJMsjpImjqJWiixHq8kyS2peqYyDS1VOfhDcIPQh98iHMMCLlIQwoGpKoSHnoAfYKvLGpqlZQpekXQy52UoWzun6lfDlaKjEFZuqm0QHbAgWTFsBawyk+VzjLdjJRmQ1BnIcdRUGS6XpKCxSaquG+72lwhOZplwGfWhOMlL8l/LBqIKFi5Kts0h5GbS0cfA0aqXIskeMEylXISCtB55GOamhVEv93zTa1RhI74En0rLKQHIPPI2OFXx5PfA0ymXQP6pvXNWWpSvpJNuyFNee33jcOvMnqI9o9nYIHDgl5x7WNCS5wPXDl4HDo1qGuYbj+Ka+TjYbIC3ydaa6RphrTVDp+ddiShCGnj/YkoLHrG1bt5ik7KzBIFXPgRz3EC67HLudUTMu0U3OnKtmUzTVyuGUmlJULYElwgPxoVcTSBG5EoDQQ/vBsWHKGq7k+UvsUnO3obIQeO8tAdXxuCi2HTt+UasmBVy8dsSWyI7b0EDrn/rO8CxHWkz/Dl07qYjVvChBZggstPBrONL75LZCXKPwT9gHUAqz5A4htXXqCkUBV1mTlOvaSUWS5hNp+cN29bbpBmJmFqk5AnRns+QmDJHWangDrd+ug+SC1NBhQAkSVQg2dujiowBJAGuqNdS1vWbMmlTcAsguGXVN6g9yEkKKC1W45HLDpuGEhWn4cL87CIP0cVEz6IXIdkXl+J1oImTQ3upebjjOGk529E0I3+z9UP7kq3LIgwo/VZGPdyEwLNiIiyr4dhaJJ3Fim0iXdkQvN3CuhdZBYCoT7/wo1l0zEbYogdQTOrmw988fTt/pkW/qnhnoiLDsHMuMkj5vo/BDDkyN3Zqsq2yMwWftZC9FoRYWHUaAWYCCZsGmSHaOV6ySbyk1OYidXQWOEW/8cALtauBy1NIzApPqV2EhY51pnUyjYAVdqGKol8qbvCl0axAQqF69YvsH0Lj4EmohKR7kMMR0xTPH/ydc90zvtpMXKajFwKV79UTEA6Kc4TFiQ49fAiAramaPYlV80cqRKeg0iuXYgpVyz6dRiOAKVsafqNj5Mopb8AinEltXll9yj0pldMGKJdFUtShDFqzQ3o4A6pDzAC4RiBNZt1f1qNjORbTSjuFlUQSkxnLoU5jKQ4ayFtjY3lQ9W52BxGG7cv0oBCSpJ/OAMaOCQg4ZU6IFY0ZTqFaC/iHXtYaP7bv3FGRvV3qNPYXhOdC2p+B7kJ0n7R7pujIUVNEKoW05bC5bfkte06oOLVY1NbMTShB08argVfS8mVGqUhNarGq2H6Mu7hFIH9ZX1KrCilUJ39Fo+o6aeX81oHUDWqxq6ArKadrABrJgxWIjThRrlEOKVUV9qRNe2DAdNQO4VJEa4iEd3mH6tOejvtfDAog2Q4SCGDk66K7hGVvG0HIjd0Dp7nFrI7JNwS7LeejAqpJlx2wqLHtZ6tIFtuzorVJFyphitDBBGENGphED2P7BAaDSfKGBj9RLCX9WnjyNylhvky4HZ4k2IV4kNTDZtuGbENMtI3LU1Gadksv3wKESnbvlKWKdAo3lawfCBkEMpMtoY5krpC2MM8ZXSLyKN7b9VkGZlaeIkV5LE7aOrHS+O2xQNqoJhCaw1gItXShDwldn4geXBSjBJqckpbIsYYyl+hbKeSudbI4yvJbBWZYpspbViBbyh1MUtfrURnHAMlOd4ovItrXO72VcQ5oIudashVzCfknZFPPktW+EfXfqUIbaaCFigskxCVgMGQsYoWM5+ZpKmEVDToUf9Ii8YDq+2FbMUASFToUPrlO5lHQHPwlFndxqJ9yEGjO2wtfsSbNyA2AMVfvMlMq0In8M0WDvSiVakT+GaCQ57yNRWU9uZ5DLtQZxqF1ZtnXE25shO0yz0ItzQMopv8wW+GW2ENcBd/iLc4i8eMNkq3GZ9IPu9juycHzNrxqmvKlEhxvTaBGxAtcTO8iLWkbE0oS7MbQTH+O20MJe1BJXO2khi1q4Lkpkech9GPF65Z6PMfZDTVuLOy1PmGddDfOZ+GGLgazNaFNhw7JsNDsggcTEeEykqqdFjIrAVN4aZE03siOB3odVog3pA0kKbMdrBHnbbsrMCADw/uRMWNNXJdiQPpCkuN2eGj/OjZ329kE0M+ZSN7R9bX9Rb0vCTIHWFqXZShf78H2rYDWTGnsUc9mGFilv5s8D4M7NcPASbq6CVmam9YP12L6VexDaT8gJ4RG8YHHoX2ncW8C4uUPgcGMDx4IjWixIPGMaBB/PP5MQ6GvDiW0XeRfLYdoKwsXVNJBUCfyqgvk44SIji1dD+ABuWSmWQa0km4sZ2roAoSSrNYUP4CbHag3ZXMyQdHz8UDyxumg+i+HVu3LLL8N0rSAjuErK5TYMLqbuiwWeHu243pOK5dqBMoitHItSpA/JdWuLpMrp49oguHgCI5BArSS1jQ3vssEudvuXvSuqOf52uK9IoRgC1nJZXMbdAcfx937oDN63qNGoCuTiEoT+kx3BSfuIoKQ1NnWRorLaj3e9fuk17WzPAs9zxGq8bhheq0rkVo3ygvaorvoWmI8+4qOfz8/nrylGaO4JpYGfOOZ2g1bgRixIxb5rV09oR3Fi2f5HDVk+U6C+yJSnGjavX9sxL2SaZMxKlh+d0YLkMIDT0g9iYpdEgedYh+X8Ed14akdx7ahlP6teWcNsBbzE5bVPlmYYohFFIOQuEEWqoQuHg0rCuPyHU/Sw3sgzoBapBqI6sFBwg2aJhmraWN9m0pRtzXrYwv3gnYruumYy6phFlOuRNaoW8XEppRpVnjlRi1RjyjMvaJZIzpJvS5Fb3Cyvl7z9+cIP2QKiNlJee6aTcIV3ry8T4bKJVs7t+o0SVBtj/TREWEuxtaaIwfuxRBS6HK7uvcdHpiRhMJf4T7QlFMMqO4hINflIi2xNhjFbqzXS1MM54GXbWqA3ZgqlxIMZuEGiG6H79G4QhUrqiQ+W3K9ul2eT1nXYD7FaEZOtFaY0+eCs9CM9ts3HYRRKiWX7Ti3xFHS4sSFVdFeoXbvDrFdVgqtVkx+qA8nAc+8kcIBue/bA41VjXSFLBHQP/tmfRdl5i1LKbKBBE3bonn0Nzr3VkWaASvyuqrCJm1nbh2NOYLSvxEgtXhk6e7HKUmRlqixhlK9+KkcPY4YBdB+bTMqhl+7cesylOtc482UpSRBm/9FsMikTVy5yB/Y0VYtg47aGvTyTRPnEsCpi5HkIJOoRhB5wRvIphBx69SobkLlMpzoXpzzKIsTlwTg+hZCpq5gDQIAjfU5UzXJ8jlKdpymWYMpSRmSyXRKFri/gyOY6KZqog69whR2HKJ4v8JalCMqNEYTqYg51kgNcK3zineIwbezJKC7A9C3QnytYqfJifJ5u4pbPe3Jpe62yzYZgUXhsI3EYOjViPZSGhH+oJR4erQIKGoQ+GlXfAg+ELBNBmu6lxONYMLXtNAYcLXknur5xjGg3mEORfBwTx2dZIqORyFJKP2M5ZoRRrjBZ7H3H9h5ZhhslpVGP3i1KQC4MIpSllJ0Ljr0engswMSa7uDnHewQGh6YwrUZJf7h9eL+lRG0fw3mEWQ/V2GJOZEVUZkpJDugAW8aKoR1CiuBRRJFkwFZvmpqnL6oBs/dE8o/6oFNH7J5g8c4OLT0wwviFt5xuQgDC2B8YIgdv63A1ImN3Sqh5X+wutdUbZE+tZCYt05vsTGU7JxVBHO0/d0ji8ftzVENkWnVu1PXZItswqwvjDtTcws0NfL99pMbNLhcnJb/GdLBkRWhM9Qj8MDbWzpByUZP0ZbEQdW3uxf0N6rY/i7yUECk6oPISC2uZmTSopZbR0zKZAu+6QSJdwwz9AcW3l2su+Ie8yeYGuDeGqDvPd8AI9HMBBSJlpRUCDyncfIspbTGdQY+/dq8RUxoanwd3ByFYvBMU63I8pbKkkaQsEIQAHXexyA1nOCJCuy8qM8V2uSMJgyd0OGwLLRAIoFmXNpLcZwiDfFHGEytLGkmq06OZmRCPi3MHGRdEkbEF+jrZbDqWwJlpNeWNJRgk5G6bZqSHYQQb8gQQ3IdGEIBQEL2ytJHksp5nPLGypLGkQv+/YCMkwFplSSNJ/ZGARICZcjEj6UTADXYC6mMhZyyhGEUyw4NCARlXlzaS3BKJuxHErSZstN2wu4uo9rUhbiQ9dIRjPKtMylgyaP9UQA4WcqQumtBHk4NnCWUJgxf7KwOowVTqUgbT6Tzt0kuD7dhLBzxpjQfj58mHexhUqutgIg0xw4+CwJo6omDkyYcTIHVzOIM8/dR+TWA7/KIz7KP1ZIP9qNXqqy9fru7HzsuJFP1+tWLPFKK7VqihESlaVdjYXh0LY+8OeliJGGcU6olilQmbbrlY4PYRNRhBdRUoCOZmEDBGU3CNOIa2Qxc2GhEoQkNoa7Qv/qLl0rR2RNewPYGQhbgOTBQe+Z1A0JK8DtQLKASdQoYJ/8YRV64GDp4NN3Dgu8LtjUQ1L1g1gZhZ3ayBNdww3NwKuA6Gd1nixc7w6p63YtnRoDiY4XZVovFa8Vg4XnnI74792u0R9EpQPMyUmK4CxsLuhtwapsJuJSgeZkrsVgFjYXeXxqlWYbgyFg+3X0/VGK+Ox8XxTDHHM3aOy9gPYalQkcUlKA5mXyj+PXIJfqG7BfVZUEkWV8A42C2SKPZdpRzLkBxML1PXaJVUK5gdXD9B+W/PhxZF5LyHnfiSAK31a4W0fsjB1mgB7dX0BQ7yVv4vKJaaIOCKRDZocVrXZHbAL365vvvqb7c88fZ60B0iTquJ7iCxAs/xree8ZF8LM0RGhQrQQWiJq9AC32I2xiz1OlmXy0phlEE6SfRZQkiW1BmwZgOqva/fkwHwmGyIQJwEemC8OL5haXWprARGmaCDAksVvUsteANcPxw8Fa9XD7rkrnWIlwhdQoTiqyfrSEKnRQPo4GOA6sovB4XykpoLZ/WxE8F3gY8MFBrhi5bK7kKPvFMoIALyOJQRepjsQzuWyyRH6GCyTjtcSTQK8V0c7C2KwiiNQy6+g4NpyiOQyu5Ct4NdbX9IKIFcfC8H7HwimUiO0cUmvcJGR/s98vjUUboYxaFuheutPDIlgA4ewLR20jhkwrvxI0MmASK9k4G8EprK7kbXzSR8ktiVVSG6uHhx6Afst5BxEynkd7DYPVobaRQy4V34rmHKrZoVhK69Jvb7tXkpuI3btetedUBeD5bK7kJ/NKM38vAz6V0M0qGpPBIlgK4x9844e/NWGotCfDeHN6dnMjmk4js4PL85+SCNQSa8B183Q2BIHGXXMDp7DVMEi3TaRb7Qs3lhmiCjGNveixm+BCSsX4rczU0XM6YYRk9nGHPAj8SMOoZS7B+VhKEvZAg/hGGG3cHPt4V0TgPYpcidvcdE1IJGaIMGM2EzokH0WOZKwaOwVY1BHFlWPIJHYesdgziyrIVkHTy+ZHMqpnUO/T1cPBHVMnwPS2x93Yymah8bHHqWbxcopX938XUFxeAfopf0f3v+cPpO68LqoHh/dXF5czV3LUHuZSV5FdTUn/7OiHcicMRKz9ak5UitZ5lYFByORbDAtkImHig/ECxS8J9//kkinqAzqsix8ziLOycSpdyOeA65QoQM6aUoVYWzfUVQnC0kjqkjiwtt3qQITYqda3ty0qvxRKUEeRw/w//ucT/16f7y/PXr9xf5TuT4ItN+4XkWZXMdWXrkm49ALhwJ+Z5vaGK9XTPRrNBGd6+kQXjIr/R6g0vy41pI+RLEzMT+AQfBRXrJ8EC890N0fhS7jE5aPELfzbJgChooUphm7uxAKvraN0IrA5/S2gEI8Rai4ejZo+msPk2NS7GzaLeTZUXiwUTA0o3APggeB1I0MuwdrDF7IwQ5mXUSxxNnWd5+pmFWlRLZ22gQEkVosdLzp4O3Tbc+u1aEvLFDFxeJJNiGxoQDh0bZdOCUa7oMmQo4cnRvgsFljm/s1rrtwdH2xkA3pRxAw1ANbD8dHXxW1gFPJKaDNB5BeiIFvxSPRL/GXhYGucpejuz07nRJ2cA1mOm5iXeohOZdi+MkVS77Gyqq5aKyoeLqFyUMl5OGKuYUwBhLVZjUalQY0WKpkTPH5nT5uqxx2cwxxhsUvmCspsWlRaMldXVaOMTUZR7x8KGyzaMvf1+urmDO3X77fP1F/7680pe3i79drZasUi6vPn3/ol99vmFNcPPp6nL1dZlBfr7+eoU3cZ4MJ0HvHx7+vz8SP/4/6crbMZraH+dLtcdmdhQl/YwV9vZudX1z/f+u9NX1t98X97/frfSLJTPp5fXXi09L/e7+9tfr5fXtN/TX6nZx+1X/9bTC/pRZ4lc9swSyes5qmLRCqbt7qObq+tcr5hxcXv/2BRr65vT09ObL6tMFuwbX+vIa768MM0Ca/NPJOAH/rt8svutX3y4+fb3SP3+9WP6if7pYXl3qV/9+tfi+grklQv7i9uYG5juRf3N7eSVGKK4D9xeX17f6p9uL+0tMXf8VtS5SxEPJZ4MLLBHx7eKmqjypiNkKOV+1zKXeX/1KEXpxcsYt79vVCuXW3e23q28r/frb4uv3y6tLVgG6vlxdrK4XMOHX629VRXFUDRM+sD3H9ur9aRcnkidE0+tv1yvmpPcXN7hIVHicPJ+Y379yyVjCpq8m42xjnpxwiKFVt+u7m+/6xd01e2OT2QJXfR1Ru8n7n2EFM+2BMKExEr5f3A9sfVNjEDGwbfg+lAhpXe4uvlylGcabNbefP3+9vbhEdeC32/u/obK8+Bt7R9DcLGfATLW/5SgD5ZJ0/W11df/5YsGs7eoCWvoKDl2+ov+W2+UBPRe7Zf5dv/t6sfp8e38zsP0kxf735f1qAXvpqyVsnQa3xER3OKJpDEM7Grbfri7+VkHUdSOOQ3udxEDX//Vf98B4/Ld/42Dx2/Xn6xFNLUuPcnJyJrpHecsnjww4v32Hbejl3/TVL8hVSP96u7iAubC6vUd19e4WF+JlBe6Mg3Bhw8XF6uLr7ZeigLDJuF+t8DASD2nLrTwziTwUm768WjQGTcRkxUdUE6a+DZ8rnlpbsz4hoX7m+XA6xPJhFFvm//7fnV+yzQwZLr2iM2DSx619FPu+cxukNkc/ri34VfF0nphztCAEhYTY8j5+3PHVHH3h2n/iQF+VzLLAOqnvyknAN5+fdXR20DJCq4IP86fRtLLgo1/mzrC9bgL5Z3MzSKrAfhiD52P3XAX4pga+CZ7Oj6P6xoocaMc3Yt1Y29XRqb+JN0PwyQ173eDpLXzkn6UZ2kFcAf8XFIgcmLFmJLG/BZ5GvkTLofrSX8ydumelhAK5STwTPdQjgP+NKgzjMKmP2CVwsIzYEIrPkTme4fm6qcP2aArNfdeO9U0Imz898PGmzgQkoAHAswmCqbIf4odxbCvO+Mxr9MYIcC+kXm+zpSf48EE+9t4IPdvbRnPDcSZQPYcHz3FoTEkgAJbhoQWKSrdkOJFKEmhTHR/GigbScI1HgLoNKMmdo0FZbIRbENd5tHzWGBMcu/DJz3wjg5EU4l3irmsk0mfywevDkmMXPvk5HZwcW6dvlZCgDlAgFfT8GD7/mWOw0gApWp1ePsWnbU3UMZxQ/MzaTnXITw/HsJFBQZvbRs+EEPMQWjAlWgd2vPH8Y/J0EkItPTqmVX6nrixlrZ1e73KOf8NP1JpJLptBdmn2hce/pc8mso00Rjz2aZ2yH9+yTdgFWkYmFx6btM+Yjjfo3XHxTq2BlBHjsVb3HPd4k72fzGrKCXLVv+456vEGfXCMPzjOP1BcLVVRpM8vWz5rX/gZt94zkhVe8WisdxzDkS4wo5/R2zn+UwWXbBKuk9+6awRVVv+eynt4dQwn6j//y7/efl/dfV/pl9f3/6b9y7/e3d/+36vFCu2F/NscJx5T8Bqs7cik3JODxX61ozgXXfSOcHSVeEkErOPAQMWtUdJ6RXRNvXoT92Rib/p6J6YVFuSw686P4v9ehuUzFDTLnHgxz20LwD9fnxFzWfGcHE6z1ontWHj1er71knmpvUOxMev2LAmsfU0+miODz7E7Lroc7Z/K9L3pqTdKdXy/SS+jPXaAt413P9e3A2VnNZrD8WR2+fv/ye5ps5vsn+KsTvd26rmXOmX7QXX+ENn77YfTd+7p6am7jdcDJ1gtnS93a5vAH3oQwoHSRsfLT5w2/c2ZHR9vzZbhKltyWAzRPPQ43D9DOVsX+fyL7Z0UWUt+35AOpph6BvRt1kw41sYxttEEZUN05g5rZjnsln6dWe6fxW6NFgTFNnHXQoZsz/BHLu54b8e742aEogOpG7ziTDs0E8cILRAAzwKe+TJsD+twNPJgq2g1ZoXsO1BjaqAANYrazJE1P2lpJ41/vfrpr8+ugz4FIQo/BT8+nRM3e4CucLC9LXz0ffX5+P3D0V+JgKyTz12YEnPu+lYCaxS+CmK+wMem7shnd9DGnzBxEtlqjv28YGIoJgBh/LI04b8/k6vu8dihbPcApsZqL2MQ/AVyr/xWpI9FLhVagjjGO5esimjyKA02rkROiZmyGpTT9Rt70+UiWvNbjfA2N0NTTw/7mCFBREUE5lVe9OGjPGAWvakq38ZaLVJHs6Pl9c3d1+vF9ep3fbn6js5I3N3f3l3dr66vlkcfj/7+cJRFbfv4AH89wKGt8QRgGfXNx1+N0EZn3yL0+CP6D/oA/Q9W+cCGX1mPX32TrK6nLz5mf2yB+eijM6D6+fx8/jp7PMv+QOfOboNmusbIOn3+D/IfKOAovSnrh6H8D5gPBB15rkTQ7P/xd4SW5iqUhHJ1lpcufCgOKUeKRukKYR3dD4Rug4Ef+6G9tT3DSb/2EseBT9NaAR+czrCAGI454K/j07cnH07Ozt+dv//HjAudnJ/X05ZExw1zNIjD2ZsPHz6cvz094WTwOQQAnbQtbmjihn5z9vb9h/fvXr/mhL5fXemXZAqI7uYdZPm352dv3p29OTlnxc6Wm6Hl8al5nQQV0W18jYVJ7gvg53F+9u7kFNJgLgD9PIbY4/T9GaRx9ubtuwE88vPkOqzDhuMPKw1nZ+9en5ydnn0YwAA8IfSd4VkOuWKVG/31mzdvzz68PRuifxV9SDGA2G/fvXv9bkgpyM4tpwQG5v/5+dmH89OTkzMRDIaY4PTk/AS21R9OmFsDGgN0vGBsVTh//+Hd+9MPsFn6z6N//P+OUAZo=END_SIMPLICITY_STUDIO_METADATA
